#include "runner.h"

static bool is_valid_cast(uint8_t source_index, uint8_t target_index)
{
    return source_index >= FIRST_INTEGER_TYPE_INDEX && source_index <= LAST_INTEGER_TYPE_INDEX && target_index >= FIRST_INTEGER_TYPE_INDEX && target_index <= LAST_INTEGER_TYPE_INDEX ||
           source_index >= FIRST_FLOAT_TYPE_INDEX && source_index <= LAST_FLOAT_TYPE_INDEX && target_index >= FIRST_FLOAT_TYPE_INDEX && target_index <= LAST_FLOAT_TYPE_INDEX ||
           source_index >= FIRST_FLOAT_TYPE_INDEX && source_index <= LAST_FLOAT_TYPE_INDEX && target_index >= FIRST_INTEGER_TYPE_INDEX && target_index <= LAST_INTEGER_TYPE_INDEX ||
           source_index >= FIRST_INTEGER_TYPE_INDEX && source_index <= LAST_INTEGER_TYPE_INDEX && target_index >= FIRST_FLOAT_TYPE_INDEX && target_index <= LAST_FLOAT_TYPE_INDEX ||
           source_index >= FIRST_INTEGER_TYPE_INDEX && source_index <= LAST_INTEGER_TYPE_INDEX && target_index == ENUMERATION_TYPE_INDEX ||
           target_index >= FIRST_INTEGER_TYPE_INDEX && target_index <= LAST_INTEGER_TYPE_INDEX && source_index == ENUMERATION_TYPE_INDEX ||
           source_index >= FIRST_FLOAT_TYPE_INDEX && source_index <= LAST_FLOAT_TYPE_INDEX && target_index == ENUMERATION_TYPE_INDEX ||
           target_index >= FIRST_FLOAT_TYPE_INDEX && target_index <= LAST_FLOAT_TYPE_INDEX && source_index == ENUMERATION_TYPE_INDEX ||
           source_index == ENUMERATION_TYPE_INDEX && target_index == ENUMERATION_TYPE_INDEX;
}

static bool cast_non_function_type_to_non_function_type(void)
{
    static uint8_t source_index = 0;
    static uint8_t target_index = 0;

    if (target_index == LAST_TYPE_INDEX)
        return false;

    format_test_name("semantics/expressions/cast/cast_%s_to_%s", types[target_index].file_friendly_name, types[source_index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function a(%s b) : %s\n"
                          "    return %s(b)\n"
                          "end\n",
                          types[source_index].name,
                          types[target_index].name,
                          types[target_index].name);

    bool is_valid_case = is_valid_cast(source_index, target_index);
    if (is_valid_case)
    {
        format_command_line_options("%s -print-semantics", test.source_paths[0]);
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: a" NEW_LINE
                           "        formal_parameter" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: b" NEW_LINE
                           "        return_type: %s" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            cast" NEW_LINE
                           "                type: %s" NEW_LINE
                           "                reference_expression" NEW_LINE
                           "                    type: %s" NEW_LINE
                           "                    name: b" NEW_LINE,
                           test.source_paths[0],
                           types[source_index].name,
                           types[target_index].name,
                           types[target_index].name,
                           types[source_index].name);
    }
    else
    {
        format_command_line_options(test.source_paths[0]);
        format_expectation(&test.expected_error,
                           "%s:25:12: Cannot cast %s to %s" NEW_LINE,
                           test.source_paths[0],
                           types[source_index].name,
                           types[target_index].name);
    }

    if (source_index == LAST_TYPE_INDEX)
    {
        target_index++;
        source_index = 0;
    }
    else
        source_index++;

    return true;
}

static void polymorphic_types(void)
{
    format_test_name("semantics/expressions/cast/polymorphic_types");

    format_source_path(0, "semantics/expressions/cast/polymorphic_types.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[P, R](P p) : R\n"
                          "    return R(p)\n"
                          "end\n"
                          "\n"
                          "function b(I8 c) : I32\n"
                          "    return a[I8, I32](c)\n"
                          "end\n");
    
    format_command_line_options("semantics/expressions/cast/polymorphic_types.owen -print-semantics");
    format_expectation(&test.expected_semantics,
                       "file" NEW_LINE
                       "    path: semantics/expressions/cast/polymorphic_types.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: P" NEW_LINE
                       "        formal_type_parameter: R" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: P" NEW_LINE
                       "            name: p" NEW_LINE
                       "        return_type_reference: R" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            cast" NEW_LINE
                       "                type_reference: R" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: p" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I8" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I8" NEW_LINE
                       "            name: p" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            cast" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I8" NEW_LINE
                       "                    name: p" NEW_LINE
                       "    function" NEW_LINE
                       "        name: b" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I8" NEW_LINE
                       "            name: c" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I8) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I8" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I8" NEW_LINE
                       "                    name: c" NEW_LINE);
}

static bool cast_literal_to_x(void)
{
    static uint8_t index = 0;
    while (true)
    {
        if (index == LAST_TYPE_INDEX)
            return false;

        bool is_valid_case = types[index].default_value && is_valid_cast(index, index);
        if (is_valid_case)
        {
            format_test_name("semantics/expressions/cast/cast_%s_literal_to_%s", types[index].file_friendly_name, types[index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "enumeration Enumeration : I32\n"
                                  "    a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "union Union\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "union Union[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "function a() : %s\n"
                                  "    return %s(%s)\n"
                                  "end\n",
                                  types[index].name,
                                  types[index].name,
                                  types[index].default_value);

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics, 
                               "file" NEW_LINE
                               "    path: %s" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    enumeration" NEW_LINE
                               "        name: Enumeration" NEW_LINE
                               "        underlying_type: I32" NEW_LINE
                               "        is_public: false" NEW_LINE
                               "        constant" NEW_LINE
                               "            name: a" NEW_LINE
                               "            value: 0" NEW_LINE
                               "    structure" NEW_LINE
                               "        name: Structure" NEW_LINE
                               "        is_public: false" NEW_LINE
                               "        field" NEW_LINE
                               "            type: I32" NEW_LINE
                               "            name: a" NEW_LINE
                               "    structure" NEW_LINE
                               "        name: Structure" NEW_LINE
                               "        is_public: false" NEW_LINE
                               "        formal_type_parameter: T" NEW_LINE
                               "        field" NEW_LINE
                               "            type_reference: T" NEW_LINE
                               "            name: a" NEW_LINE
                               "    union" NEW_LINE
                               "        name: Union" NEW_LINE
                               "        is_public: false" NEW_LINE
                               "        field" NEW_LINE
                               "            type: I32" NEW_LINE
                               "            name: a" NEW_LINE
                               "    union" NEW_LINE
                               "        name: Union" NEW_LINE
                               "        is_public: false" NEW_LINE
                               "        formal_type_parameter: T" NEW_LINE
                               "        field" NEW_LINE
                               "            type_reference: T" NEW_LINE
                               "            name: a" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        return_type: %s" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            cast" NEW_LINE
                               "                type: %s" NEW_LINE
                               "                %s_literal" NEW_LINE
                               "                    type: %s" NEW_LINE
                               "                    value: 0" NEW_LINE,
                               test.source_paths[0],
                               types[index].name,
                               types[index].name,
                               types[index].file_friendly_default_value_name,
                               types[index].name);
        }

        index++;
        if (is_valid_case)
            return true;
    }

    return false;
}

static void matching_monomorphic_function(void)
{
    format_test_name("semantics/expressions/cast/matching_monomorphic_function");

    format_source_path(0, "semantics/expressions/cast/matching_monomorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b) : I32\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c() : Function(I32) : I32\n"
                          "    return Function(I32) : I32(a)\n"
                          "end\n");
    
    format_command_line_options("semantics/expressions/cast/matching_monomorphic_function.owen -print-semantics");
    format_expectation(&test.expected_semantics,
                       "file" NEW_LINE
                       "    path: semantics/expressions/cast/matching_monomorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        return_type: Function(I32) : I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            cast" NEW_LINE
                       "                type: Function(I32) : I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE);
}

static void matching_polymorphic_function(void)
{
    format_test_name("semantics/expressions/cast/matching_polymorphic_function");

    format_source_path(0, "semantics/expressions/cast/matching_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](T b) : T\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c() : Function(I32) : I32\n"
                          "    return Function(I32) : I32(a)\n"
                          "end\n");
    
    format_command_line_options("semantics/expressions/cast/matching_polymorphic_function.owen -print-semantics");
    format_expectation(&test.expected_semantics,
                       "file" NEW_LINE
                       "    path: semantics/expressions/cast/matching_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        return_type: Function(I32) : I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            cast" NEW_LINE
                       "                type: Function(I32) : I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE);
}

static void formal_type_parameter_nested_in_compound(void)
{
    format_test_name("semantics/expressions/cast/formal_type_parameter_nested_in_compound");

    format_source_path(0, "semantics/expressions/cast/formal_type_parameter_nested_in_compound.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure A[T]\n"
                          "    T t\n"
                          "end\n"
                          "\n"
                          "function a[T](A[T] b) : T\n"
                          "    return b.t\n"
                          "end\n"
                          "\n"
                          "function c() : Function(A[I32]) : I32\n"
                          "    return Function(A[I32]) : I32(a)\n"
                          "end\n");
    
    format_command_line_options("semantics/expressions/cast/formal_type_parameter_nested_in_compound.owen -print-semantics");
    format_expectation(&test.expected_semantics,
                       "file" NEW_LINE
                       "    path: semantics/expressions/cast/formal_type_parameter_nested_in_compound.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        field" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: t" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: t" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: A[T]" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            field_access" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                field: t" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: A[I32]" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            field_access" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: A[I32]" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                field: t" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        return_type: Function(A[I32]) : I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            cast" NEW_LINE
                       "                type: Function(A[I32]) : I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(A[I32]) : I32" NEW_LINE
                       "                    name: a" NEW_LINE);
}

static void formal_type_parameter_not_specified_by_actual_parameters(void)
{
    format_test_name("semantics/expressions/cast/formal_type_parameter_not_specified_by_actual_parameters");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T1, T2](T1 b) : T2\n"
                          "    return b + 2\n"
                          "end\n"
                          "\n"
                          "function c() : Function(I32) : I32\n"
                          "    return Function(I32) : I32(a)\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/cast/formal_type_parameter_not_specified_by_actual_parameters.owen");

    format_expectation(&test.expected_error, 
                       "%s:9:32: T2 could not be inferred from the call site. Specify it explicitly." NEW_LINE,
                       test.source_paths[0]);
}

static void formal_type_parameter_redefined_by_actual_parameter(void)
{
    format_test_name("semantics/expressions/cast/formal_type_parameter_redefined_by_actual_parameter");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](T b, T c) : T\n"
                          "    return b + c\n"
                          "end\n"
                          "\n"
                          "function d(I32 e, F32 f) : Function(I32, F32) : I32\n"
                          "    return Function(I32, F32) : I32(a)\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/cast/formal_type_parameter_redefined_by_actual_parameter.owen");

    format_expectation(&test.expected_error, 
                       "%s:9:37: T redefined as F32. It was originally I32." NEW_LINE,
                       test.source_paths[0]);
}

bool semantics_expressions_cast(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            if (cast_non_function_type_to_non_function_type())
                break;

            state++;

        case 1:
            polymorphic_types();
            state++;
            break;

        case 2:
            if (cast_literal_to_x())
                break;

            state++;

        case 3:
            matching_monomorphic_function();
            state++;
            break;

        case 4:
            matching_polymorphic_function();
            state++;
            break;

        case 5:
            formal_type_parameter_nested_in_compound();
            state++;
            break;

        case 6:
            formal_type_parameter_not_specified_by_actual_parameters();
            state++;
            break;

        case 7:
            formal_type_parameter_redefined_by_actual_parameter();
            state++;
            break;

        default:
            return false;
    }

    return true;
}
