#include "runner.h"

static bool assign_non_pointer_x_typed_expression_to_non_pointer_x_typed_field(void)
{
    static uint8_t index = 0;
    while (index < FIRST_POINTER_TYPE_INDEX && !types[index].default_value_name)
        index++;

    if (index == FIRST_POINTER_TYPE_INDEX)
        return false;

    format_test_name("semantics/expressions/compound_literal/assign_%s_typed_expression_to_%s_typed_field", types[index].file_friendly_name, types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure A\n"
                          "    %s a\n"
                          "end\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function do_stuff(%s b) : A\n"
                          "    return { a = b }\n"
                          "end", 
                          types[index].name,
                          types[index].name);

    format_command_line_options("%s -print-semantics", test.source_paths[0]);
    if (!strcmp("Structure", types[index].name))
    {
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: A" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: a" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: do_stuff" NEW_LINE
                           "        formal_parameter" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: b" NEW_LINE
                           "        return_type: A" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            compound_literal" NEW_LINE
                           "                type: A" NEW_LINE
                           "                field_initializer" NEW_LINE
                           "                    type: %s" NEW_LINE
                           "                    name: a" NEW_LINE
                           "                    reference_expression" NEW_LINE
                           "                        type: %s" NEW_LINE
                           "                        name: b" NEW_LINE,
                           test.source_paths[0],
                           types[index].name,
                           types[index].name,
                           types[index].name,
                           types[index].name);
    }
    else if (!strcmp("Structure[I32]", types[index].name))
    {
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: A" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: a" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        actual_type_parameter: I32" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: do_stuff" NEW_LINE
                           "        formal_parameter" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: b" NEW_LINE
                           "        return_type: A" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            compound_literal" NEW_LINE
                           "                type: A" NEW_LINE
                           "                field_initializer" NEW_LINE
                           "                    type: %s" NEW_LINE
                           "                    name: a" NEW_LINE
                           "                    reference_expression" NEW_LINE
                           "                        type: %s" NEW_LINE
                           "                        name: b" NEW_LINE,
                           test.source_paths[0],
                           types[index].name,
                           types[index].name,
                           types[index].name,
                           types[index].name);
    }
    else if (!strcmp("Union", types[index].name))
    {
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: A" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: a" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: do_stuff" NEW_LINE
                           "        formal_parameter" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: b" NEW_LINE
                           "        return_type: A" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            compound_literal" NEW_LINE
                           "                type: A" NEW_LINE
                           "                field_initializer" NEW_LINE
                           "                    type: %s" NEW_LINE
                           "                    name: a" NEW_LINE
                           "                    reference_expression" NEW_LINE
                           "                        type: %s" NEW_LINE
                           "                        name: b" NEW_LINE,
                           test.source_paths[0],
                           types[index].name,
                           types[index].name,
                           types[index].name,
                           types[index].name);
    }
    else if (!strcmp("Union[I32]", types[index].name))
    {
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: A" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: a" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        actual_type_parameter: I32" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: do_stuff" NEW_LINE
                           "        formal_parameter" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: b" NEW_LINE
                           "        return_type: A" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            compound_literal" NEW_LINE
                           "                type: A" NEW_LINE
                           "                field_initializer" NEW_LINE
                           "                    type: %s" NEW_LINE
                           "                    name: a" NEW_LINE
                           "                    reference_expression" NEW_LINE
                           "                        type: %s" NEW_LINE
                           "                        name: b" NEW_LINE,
                           test.source_paths[0],
                           types[index].name,
                           types[index].name,
                           types[index].name,
                           types[index].name);
    }
    else
    {
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: A" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: a" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: do_stuff" NEW_LINE
                           "        formal_parameter" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: b" NEW_LINE
                           "        return_type: A" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            compound_literal" NEW_LINE
                           "                type: A" NEW_LINE
                           "                field_initializer" NEW_LINE
                           "                    type: %s" NEW_LINE
                           "                    name: a" NEW_LINE
                           "                    reference_expression" NEW_LINE
                           "                        type: %s" NEW_LINE
                           "                        name: b" NEW_LINE,
                           test.source_paths[0],
                           types[index].name,
                           types[index].name,
                           types[index].name,
                           types[index].name);
    }

    index++;
    return true;
}

static bool assign_x_typed_expression_to_pointer_x_typed_field(void)
{
    static uint8_t expression_type_index = FIRST_POINTER_TYPE_INDEX;
    static uint8_t field_type_index = FIRST_POINTER_TYPE_INDEX;

    if (expression_type_index > LAST_POINTER_TYPE_INDEX)
        return false;

    format_test_name("semantics/expressions/compound_literal/assign_%s_typed_expression_to_%s_typed_field", types[expression_type_index].file_friendly_name, types[field_type_index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                            "namespace Abc\n"
                            "\n"
                            "structure A\n"
                            "    %s a\n"
                            "end\n"
                            "\n"
                            "function do_stuff(%s b) : A\n"
                            "    return { a = b }\n"
                            "end", 
                            types[expression_type_index].name,
                            types[field_type_index].name);

    if (pointer_type_is_compatible_with(field_type_index, expression_type_index))
    {
        format_command_line_options("%s -print-semantics", test.source_paths[0]);
        format_expectation(&test.expected_semantics, 
                            "file" NEW_LINE
                            "    path: %s" NEW_LINE
                            "    namespace: Abc" NEW_LINE
                            "    structure" NEW_LINE
                            "        name: A" NEW_LINE
                            "        is_public: false" NEW_LINE
                            "        field" NEW_LINE
                            "            type: %s" NEW_LINE
                            "            name: a" NEW_LINE
                            "    function" NEW_LINE
                            "        name: do_stuff" NEW_LINE
                            "        formal_parameter" NEW_LINE
                            "            type: %s" NEW_LINE
                            "            name: b" NEW_LINE
                            "        return_type: A" NEW_LINE
                            "        return_statement" NEW_LINE
                            "            compound_literal" NEW_LINE
                            "                type: A" NEW_LINE
                            "                field_initializer" NEW_LINE
                            "                    type: %s" NEW_LINE
                            "                    name: a" NEW_LINE
                            "                    reference_expression" NEW_LINE
                            "                        type: %s" NEW_LINE
                            "                        name: b" NEW_LINE,
                            test.source_paths[0],
                            types[expression_type_index].name,
                            types[field_type_index].name,
                            types[expression_type_index].name,
                            types[field_type_index].name);
    }
    else
    {
        format_command_line_options(test.source_paths[0]);
        format_expectation(&test.expected_error, 
                           "%s:9:18: %s expected but found %s." NEW_LINE,
                           test.source_paths[0],
                           types[expression_type_index].name,
                           types[field_type_index].name);
    }

    if (field_type_index > LAST_POINTER_TYPE_INDEX)
    {
        field_type_index = FIRST_POINTER_TYPE_INDEX;
        expression_type_index++;
    }
    else
        field_type_index++;

    return true;
}

static bool assign_non_pointer_x_typed_expression_to_non_pointer_y_typed_field(void)
{
    static uint8_t lhs_index = 0;
    static uint8_t rhs_index = 0;

    while (true)
    {
        if (lhs_index == FIRST_POINTER_TYPE_INDEX)
            return false;

        bool is_valid_case = lhs_index != rhs_index;
        if (is_valid_case)
        {
            format_test_name("semantics/expressions/compound_literal/assign_%s_typed_expression_to_%s_typed_field", types[rhs_index].file_friendly_name, types[lhs_index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    %s a\n"
                                  "end\n"
                                  "\n"
                                  "enumeration Enumeration : I32\n"
                                  "    a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "union Union\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "union Union[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "function do_stuff(%s b) : A\n"
                                  "    return { a = b }\n"
                                  "end", 
                                  types[lhs_index].name,
                                  types[rhs_index].name);

            format_command_line_options("%s", test.source_paths[0]);
            format_expectation(&test.expected_error, 
                               "%s:29:18: %s expected but found %s." NEW_LINE,
                               test.source_paths[0],
                               types[lhs_index].name,
                               types[rhs_index].name);
        }

        if (rhs_index == FIRST_POINTER_TYPE_INDEX)
        {
            rhs_index = 0;
            lhs_index++;
        }
        else
            rhs_index++;

        if (is_valid_case)
            return true;
    }

    return false;
}

static bool assign_non_typed_expression_to_x_typed_field(void)
{
    static uint8_t index = 0;
    if (index == LAST_TYPE_INDEX)
        return false;

    format_test_name("semantics/expressions/compound_literal/assign_non_typed_expression_to_%s_typed_field", types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure A\n"
                          "    %s a\n"
                          "end\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function f()\n"
                          "end\n"
                          "\n"
                          "function do_stuff() : A\n"
                          "    return { a = f() }\n"
                          "end", 
                          types[index].name,
                          types[index].name);

    format_command_line_options("%s", test.source_paths[0]);
    format_expectation(&test.expected_error, 
                       "%s:32:19: %s expected but found none." NEW_LINE,
                       test.source_paths[0],
                       types[index].name);

    index++;
    return true;
}

static bool assign_tuple_typed_expression_to_x_typed_field(void)
{
    static uint8_t index = 0;
    if (index == LAST_TYPE_INDEX)
        return false;

    format_test_name("semantics/expressions/compound_literal/assign_tuple_typed_expression_to_%s_typed_field", types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure A\n"
                          "    %s a\n"
                          "end\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function f() : I32, I32\n"
                          "    return 0, 0\n"
                          "end\n"
                          "\n"
                          "function do_stuff() : A\n"
                          "    return { a = f() }\n"
                          "end", 
                          types[index].name,
                          types[index].name);

    format_command_line_options("%s", test.source_paths[0]);
    format_expectation(&test.expected_error, 
                       "%s:33:19: %s expected but found I32, I32." NEW_LINE,
                       test.source_paths[0],
                       types[index].name);

    index++;
    return true;
}

static void field_initialized_multiple_times(void)
{
    format_test_name("semantics/expressions/compound_literal/field_initialized_multiple_times");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure A\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "function do_stuff() : A\n"
                          "    return { a = 0, a = 1 }\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/compound_literal/field_initialized_multiple_times.owen");
    format_expectation(&test.expected_error, 
                       "semantics/expressions/compound_literal/field_initialized_multiple_times.owen:9:21: a is initialized multiple times." NEW_LINE);
}

static bool x_type_compatible_literal_assigned_to_x_typed_field(void)
{
    static uint8_t index = 0;

    while (true)
    {
        if (index == LAST_TYPE_INDEX)
            return false;

        bool is_valid_case = types[index].file_friendly_default_value_name != NULL;
        if (is_valid_case)
        {
            format_test_name("semantics/expressions/compound_literal/%s_type_%s_literal_assigned_to_%s_typed_field", types[index].file_friendly_name, types[index].file_friendly_default_value_name, types[index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    %s a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "union Union\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "union Union[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "function do_stuff() : A\n"
                                  "    return { a = %s }\n"
                                  "end", 
                                  types[index].name,
                                  types[index].default_value);

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            if (!strcmp("Structure[I32]", types[index].name))
            {
                format_expectation(&test.expected_semantics, 
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: A" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: %s" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        actual_type_parameter: I32" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: do_stuff" NEW_LINE
                                   "        return_type: A" NEW_LINE
                                   "        return_statement" NEW_LINE
                                   "            compound_literal" NEW_LINE
                                   "                type: A" NEW_LINE
                                   "                field_initializer" NEW_LINE
                                   "                    type: %s" NEW_LINE
                                   "                    name: a" NEW_LINE
                                   "                    compound_literal" NEW_LINE
                                   "                        type: %s" NEW_LINE
                                   "                        field_initializer" NEW_LINE
                                   "                            type: I32" NEW_LINE
                                   "                            name: a" NEW_LINE
                                   "                            integer_literal" NEW_LINE
                                   "                                type: I32" NEW_LINE
                                   "                                value: 0" NEW_LINE,
                                   test.source_paths[0],
                                   types[index].name,
                                   types[index].name,
                                   types[index].name);
            }
            else if (!strcmp("Union[I32]", types[index].name))
            {
                format_expectation(&test.expected_semantics, 
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: A" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: %s" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        actual_type_parameter: I32" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: do_stuff" NEW_LINE
                                   "        return_type: A" NEW_LINE
                                   "        return_statement" NEW_LINE
                                   "            compound_literal" NEW_LINE
                                   "                type: A" NEW_LINE
                                   "                field_initializer" NEW_LINE
                                   "                    type: %s" NEW_LINE
                                   "                    name: a" NEW_LINE
                                   "                    compound_literal" NEW_LINE
                                   "                        type: %s" NEW_LINE
                                   "                        field_initializer" NEW_LINE
                                   "                            type: I32" NEW_LINE
                                   "                            name: a" NEW_LINE
                                   "                            integer_literal" NEW_LINE
                                   "                                type: I32" NEW_LINE
                                   "                                value: 0" NEW_LINE,
                                   test.source_paths[0],
                                   types[index].name,
                                   types[index].name,
                                   types[index].name);
            }
            else if (types[index].default_value_name && !strcmp("Compound", types[index].default_value_name))
            {
                format_expectation(&test.expected_semantics, 
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: A" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: %s" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: do_stuff" NEW_LINE
                                   "        return_type: A" NEW_LINE
                                   "        return_statement" NEW_LINE
                                   "            compound_literal" NEW_LINE
                                   "                type: A" NEW_LINE
                                   "                field_initializer" NEW_LINE
                                   "                    type: %s" NEW_LINE
                                   "                    name: a" NEW_LINE
                                   "                    compound_literal" NEW_LINE
                                   "                        type: %s" NEW_LINE
                                   "                        field_initializer" NEW_LINE
                                   "                            type: I32" NEW_LINE
                                   "                            name: a" NEW_LINE
                                   "                            integer_literal" NEW_LINE
                                   "                                type: I32" NEW_LINE
                                   "                                value: 0" NEW_LINE,
                                   test.source_paths[0],
                                   types[index].name,
                                   types[index].name,
                                   types[index].name);
            }
            else
            {
                format_expectation(&test.expected_semantics, 
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: A" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: %s" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: do_stuff" NEW_LINE
                                   "        return_type: A" NEW_LINE
                                   "        return_statement" NEW_LINE
                                   "            compound_literal" NEW_LINE
                                   "                type: A" NEW_LINE
                                   "                field_initializer" NEW_LINE
                                   "                    type: %s" NEW_LINE
                                   "                    name: a" NEW_LINE
                                   "                    %s_literal" NEW_LINE
                                   "                        type: %s" NEW_LINE
                                   "                        value: 0" NEW_LINE,
                                   test.source_paths[0],
                                   types[index].name,
                                   types[index].name,
                                   types[index].file_friendly_default_value_name,
                                   types[index].name);
            }
        }

        index++;
        if (is_valid_case)
            return true;
    }

    return false;
}

static bool x_type_incompatible_literal_assigned_to_x_typed_field(void)
{
    static uint8_t lhs_index = 0;
    static uint8_t rhs_index = 0;

    while (true)
    {
        if (lhs_index == LAST_TYPE_INDEX)
            return false;

        bool is_valid_case = types[lhs_index].file_friendly_default_value_name &&
                             types[lhs_index].default_value &&
                             types[rhs_index].file_friendly_default_value_name &&
                             types[rhs_index].default_value &&
                             strcmp(types[lhs_index].default_value_name, types[rhs_index].default_value_name);

        if (is_valid_case)
        {
            format_test_name("semantics/expressions/compound_literal/%s_type_%s_literal_assigned_to_%s_typed_field", types[rhs_index].file_friendly_name, types[rhs_index].file_friendly_default_value_name, types[lhs_index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    %s a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "union Union\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "union Union[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "function do_stuff() : A\n"
                                  "    return { a = %s }\n"
                                  "end", 
                                  types[lhs_index].name,
                                  types[rhs_index].default_value);

            format_command_line_options("%s", test.source_paths[0]);
            format_expectation(&test.expected_error, 
                                "%s:25:18: Cannot infer literal as %s." NEW_LINE,
                                test.source_paths[0],
                                types[lhs_index].name);
        }

        if (rhs_index == LAST_TYPE_INDEX)
        {
            rhs_index = 0;
            lhs_index++;
        }
        else
            rhs_index++;

        if (is_valid_case)
            return true;
    }

    return false;
}

static void monomorphic_literal_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/compound_literal/monomorphic_literal_in_polymorphic_function");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure A\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "function a[T](I32 b) : A\n"
                          "    return { a = b }\n"
                          "end\n"
                          "\n"
                          "function c(I32 d) : A\n"
                          "    return a[I32](d)\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/compound_literal/monomorphic_literal_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/compound_literal/monomorphic_literal_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: a" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: A" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            compound_literal" NEW_LINE
                       "                field_initializer" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: A" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            compound_literal" NEW_LINE
                       "                type: A" NEW_LINE
                       "                field_initializer" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: A" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: A" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32) : A" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: d" NEW_LINE);
}

bool semantics_expressions_compound_literal(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            if (assign_non_pointer_x_typed_expression_to_non_pointer_x_typed_field())
                break;
            
            state++;
            
        case 1:
            if (assign_x_typed_expression_to_pointer_x_typed_field())
                break;
            
            state++;

        case 2:
            if (assign_non_pointer_x_typed_expression_to_non_pointer_y_typed_field())
                break;

            state++;

        case 3:
            if (assign_non_typed_expression_to_x_typed_field())
                break;

            state++;

        case 4:
            if (assign_tuple_typed_expression_to_x_typed_field())
                break;

            state++;

        case 5:
            field_initialized_multiple_times();
            state++;
            break;

        case 6:
            if (x_type_compatible_literal_assigned_to_x_typed_field())
                break;

            state++;

        case 7:
            if (x_type_incompatible_literal_assigned_to_x_typed_field())
                break;

            state++;

        case 8:
            monomorphic_literal_in_polymorphic_function();
            state++;
            break;

        default:
            return false;
    }

    return true;
}
