#include "runner.h"

static bool x_typed_expression(void)
{    
    static uint8_t index = 0;
    if (index == TYPES_LENGTH)
        return false;

    format_test_name("semantics/expressions/not/%s_typed_expression", types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function b(%s c) : Bool\n"
                          "    return !c\n"
                          "end", 
                          types[index].name);

    if (!strcmp("Bool", types[index].name))
    {
        format_command_line_options("%s -print-semantics", test.source_paths[0]);
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: semantics/expressions/not/bool_typed_expression.owen" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: b" NEW_LINE
                           "        formal_parameter" NEW_LINE
                           "            type: Bool" NEW_LINE
                           "            name: c" NEW_LINE
                           "        return_type: Bool" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            not" NEW_LINE
                           "                type: Bool" NEW_LINE
                           "                reference_expression" NEW_LINE
                           "                    type: Bool" NEW_LINE
                           "                    name: c" NEW_LINE);
    }
    else
    {
        format_command_line_options(test.source_paths[0]);
        format_expectation(&test.expected_error, 
                           "%s:25:13: Bool expected but found %s." NEW_LINE,
                           test.source_paths[0],
                           types[index].name);
    }

    index++;
    
    return true;
}

bool semantics_expressions_not(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            if (x_typed_expression())
                break;

            state++;

        default:
            return false;
    }

    return true;
}
