#include "runner.h"

static bool access_field_of_non_compound_type(void)
{
    static uint8_t type_index = 0;
    while (true)
    {
        if (type_index == TYPES_LENGTH - 1)
            return false;

        bool is_valid_case = !types[type_index].default_value_name || strcmp("Compound", types[type_index].default_value_name);
        if (is_valid_case)
        {
            format_test_name("semantics/expressions/field_access/access_field_of_%s", types[type_index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "enumeration Enumeration : I32\n"
                                  "    a\n"
                                  "end\n"
                                  "\n"
                                  "function a(%s b) : Enumeration\n"
                                  "    return b.a\n"
                                  "end",
                                  types[type_index].name);

            format_command_line_options(test.source_paths[0]);

            if (type_index >= FIRST_POINTER_TYPE_INDEX && type_index <= LAST_POINTER_TYPE_INDEX)
            {
                format_expectation(&test.expected_error, 
                                   "%s:9:12: %s is not a pointer to a compound type." NEW_LINE,
                                   test.source_paths[0],
                                   types[type_index].name);
            }
            else
            {
                format_expectation(&test.expected_error, 
                                   "%s:9:12: %s is not a compound type." NEW_LINE,
                                   test.source_paths[0],
                                   types[type_index].name);
            }
        }

        type_index++;
        if (is_valid_case)
            return true;
    }
}

static void access_field_of_monomorphic_structure(void)
{
    format_test_name("semantics/expressions/field_access/access_field_of_monomorphic_structure");

    format_source_path(0, "semantics/expressions/field_access/access_field_of_monomorphic_structure.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure A\n"
                          "    I32 b\n"
                          "end\n"
                          "\n"
                          "function do_stuff(A a) : I32\n"
                          "    return a.b\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/field_access/access_field_of_monomorphic_structure.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/field_access/access_field_of_monomorphic_structure.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: do_stuff" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: A" NEW_LINE
                       "            name: a" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            field_access" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: A" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                field: b" NEW_LINE);
}

static void access_field_of_polymorphic_structure(void)
{
    format_test_name("semantics/expressions/field_access/access_field_of_polymorphic_structure");

    format_source_path(0, "semantics/expressions/field_access/access_field_of_polymorphic_structure.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure A[T]\n"
                          "    T b\n"
                          "end\n"
                          "\n"
                          "function do_stuff(A[I32] a) : I32\n"
                          "    return a.b\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/field_access/access_field_of_polymorphic_structure.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/field_access/access_field_of_polymorphic_structure.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        field" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: b" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: do_stuff" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: A[I32]" NEW_LINE
                       "            name: a" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            field_access" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: A[I32]" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                field: b" NEW_LINE);
}

static void access_field_of_monomorphic_union(void)
{
    format_test_name("semantics/expressions/field_access/access_field_of_monomorphic_union");

    format_source_path(0, "semantics/expressions/field_access/access_field_of_monomorphic_union.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "union A\n"
                          "    I32 b\n"
                          "end\n"
                          "\n"
                          "function do_stuff(A a) : I32\n"
                          "    return a.b\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/field_access/access_field_of_monomorphic_union.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/field_access/access_field_of_monomorphic_union.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    union" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: do_stuff" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: A" NEW_LINE
                       "            name: a" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            field_access" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: A" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                field: b" NEW_LINE);
}

static void access_field_of_polymorphic_union(void)
{
    format_test_name("semantics/expressions/field_access/access_field_of_polymorphic_union");

    format_source_path(0, "semantics/expressions/field_access/access_field_of_polymorphic_union.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "union A[T]\n"
                          "    T b\n"
                          "end\n"
                          "\n"
                          "function do_stuff(A[I32] a) : I32\n"
                          "    return a.b\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/field_access/access_field_of_polymorphic_union.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/field_access/access_field_of_polymorphic_union.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    union" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        field" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: b" NEW_LINE
                       "    union" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: do_stuff" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: A[I32]" NEW_LINE
                       "            name: a" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            field_access" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: A[I32]" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                field: b" NEW_LINE);
}

static void access_length_field_of_array_types(void)
{
    format_test_name("semantics/expressions/field_access/access_length_field_of_array_types");

    format_source_path(0, "semantics/expressions/field_access/access_length_field_of_array_types.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a([]I32 b, [2]I32 c) : U32, U32\n"
                          "    return b.length, c.length\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/field_access/access_length_field_of_array_types.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/field_access/access_length_field_of_array_types.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: []I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: [2]I32" NEW_LINE
                       "            name: c" NEW_LINE
                       "        return_type: U32" NEW_LINE
                       "        return_type: U32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            field_access" NEW_LINE
                       "                type: U32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: []I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                field: length" NEW_LINE
                       "            field_access" NEW_LINE
                       "                type: U32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: [2]I32" NEW_LINE
                       "                    name: c" NEW_LINE
                       "                field: length" NEW_LINE);
}

static void access_capacity_field_of_dynamic_array_type(void)
{
    format_test_name("semantics/expressions/field_access/access_capacity_field_of_dynamic_array_type");

    format_source_path(0, "semantics/expressions/field_access/access_capacity_field_of_dynamic_array_type.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a([]I32 b) : U32\n"
                          "    return b.capacity\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/field_access/access_capacity_field_of_dynamic_array_type.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/field_access/access_capacity_field_of_dynamic_array_type.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: []I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: U32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            field_access" NEW_LINE
                       "                type: U32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: []I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                field: capacity" NEW_LINE);
}

static void access_elements_field_of_dynamic_array_type(void)
{
    format_test_name("semantics/expressions/field_access/access_elements_field_of_dynamic_array_type");

    format_source_path(0, "semantics/expressions/field_access/access_elements_field_of_dynamic_array_type.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a([]I32 b) : #I32\n"
                          "    return b.elements\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/field_access/access_elements_field_of_dynamic_array_type.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/field_access/access_elements_field_of_dynamic_array_type.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: []I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: #I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            field_access" NEW_LINE
                       "                type: #I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: []I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                field: elements" NEW_LINE);
}

static void access_undefined_field_of_dynamic_array_type(void)
{
    format_test_name("semantics/expressions/field_access/access_undefined_field_of_dynamic_array_type");

    format_source_path(0, "semantics/expressions/field_access/access_undefined_field_of_dynamic_array_type.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a([]I32 b) : #I32\n"
                          "    return b.asdf\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/field_access/access_undefined_field_of_dynamic_array_type.owen");
    format_expectation(&test.expected_error, 
                       "semantics/expressions/field_access/access_undefined_field_of_dynamic_array_type.owen:5:14: length, capacity or elements expected." NEW_LINE);
}

static void access_undefined_field_of_fixed_array_type(void)
{
    format_test_name("semantics/expressions/field_access/access_undefined_field_of_fixed_array_type");

    format_source_path(0, "semantics/expressions/field_access/access_undefined_field_of_fixed_array_type.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a([2]I32 b) : #I32\n"
                          "    return b.asdf\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/field_access/access_undefined_field_of_fixed_array_type.owen");
    format_expectation(&test.expected_error, 
                       "semantics/expressions/field_access/access_undefined_field_of_fixed_array_type.owen:5:14: length expected." NEW_LINE);
}

static bool access_field_of_pointer_to_compound(void)
{
    static uint8_t state;
    switch (state++)
    {
        case 0:
            format_test_name("semantics/expressions/field_access/access_field_of_pointer_readable_to_compound");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "function a(#?A b) : I32\n"
                                  "    return b.a\n"
                                  "end");

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics,
                               "file" NEW_LINE
                               "    path: %s" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    structure" NEW_LINE
                               "        name: A" NEW_LINE
                               "        is_public: false" NEW_LINE
                               "        field" NEW_LINE
                               "            type: I32" NEW_LINE
                               "            name: a" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: #?A" NEW_LINE
                               "            name: b" NEW_LINE
                               "        return_type: I32" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            field_access" NEW_LINE
                               "                type: I32" NEW_LINE
                               "                reference_expression" NEW_LINE
                               "                    type: #?A" NEW_LINE
                               "                    name: b" NEW_LINE
                               "                field: a" NEW_LINE,
                               test.source_paths[0]);

            return true;

        case 1:
            format_test_name("semantics/expressions/field_access/access_field_of_pointer_to_compound");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "function a(#A b) : I32\n"
                                  "    return b.a\n"
                                  "end");

            format_command_line_options(test.source_paths[0]);
            format_expectation(&test.expected_error, 
                               "%s:9:12: Missing readable privilege (?) from #A." NEW_LINE,
                               test.source_paths[0]);

            return true;

        default:
            return false;
    }
}

bool semantics_expressions_field_access(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            if (access_field_of_non_compound_type())
                break;

            state++;

        case 1:
            access_field_of_monomorphic_structure();
            state++;
            break;

        case 2:
            access_field_of_polymorphic_structure();
            state++;
            break;

        case 3:
            access_field_of_monomorphic_union();
            state++;
            break;

        case 4:
            access_field_of_polymorphic_union();
            state++;
            break;

        case 5:
            access_length_field_of_array_types();
            state++;
            break;

        case 6:
            access_capacity_field_of_dynamic_array_type();
            state++;
            break;

        case 7:
            access_elements_field_of_dynamic_array_type();
            state++;
            break;

        case 8:
            access_undefined_field_of_dynamic_array_type();
            state++;
            break;

        case 9:
            access_undefined_field_of_fixed_array_type();
            state++;
            break;

        case 10:
            if (access_field_of_pointer_to_compound())
                break;

            state++;
            
        default:
            return false;
    }

    return true;
}
