#include "runner.h"

static void polymorphic_and_monomorphic_return_types(void)
{
    format_test_name("semantics/statements/return/polymorphic_and_monomorphic_return_types");

    format_source_path(0, "semantics/statements/return/polymorphic_and_monomorphic_return_types.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](T b, I32 c) : T, I32\n"
                          "    return b, c\n"
                          "end\n"
                          "\n"
                          "function d(I32 e)\n"
                          "    e, e = a(e, e)\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/polymorphic_and_monomorphic_return_types.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/return/polymorphic_and_monomorphic_return_types.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: b" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: I32" NEW_LINE
                       "            name: c" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_type_reference: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: c" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: c" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: c" NEW_LINE
                       "    function" NEW_LINE
                       "        name: d" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: e" NEW_LINE
                       "        assignment_statement" NEW_LINE
                       "            operator: =" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: e" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: e" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32, I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32, I32) : I32, I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: e" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: e" NEW_LINE);
}

static void return_call_to_function_that_returns_multiple_values_matching_return_types(void)
{
    format_test_name("semantics/statements/return/return_call_to_function_that_returns_multiple_values_matching_return_types");

    format_source_path(0, "semantics/statements/return/return_call_to_function_that_returns_multiple_values_matching_return_types.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a() : I32, I32\n"
                          "    return 0, 0\n"
                          "end\n"
                          "\n"
                          "function b() : I32, I32\n"
                          "    return a()\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_call_to_function_that_returns_multiple_values_matching_return_types.owen");
    format_expectation(&test.expected_error, 
                       "%s:9:13: 2 expressions expected but found 1." NEW_LINE,
                       test.source_paths[0]);
}

static void return_call_to_function_that_returns_no_value(void)
{
    format_test_name("semantics/statements/return/return_call_to_function_that_returns_no_value");

    format_source_path(0, "semantics/statements/return/return_call_to_function_that_returns_no_value.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "end\n"
                          "\n"
                          "function b() : I32\n"
                          "    return a()\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_call_to_function_that_returns_no_value.owen");
    format_expectation(&test.expected_error, 
                       "%s:8:13: I32 expected but found none." NEW_LINE,
                       test.source_paths[0]);
}

static void return_multiple_values_too_few(void)
{
    format_test_name("semantics/statements/return/return_multiple_values_too_few");

    format_source_path(0, "semantics/statements/return/return_multiple_values_too_few.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b) : I32, I32, I32\n"
                          "    return b\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_multiple_values_too_few.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:12: 3 expressions expected but found 1." NEW_LINE,
                       test.source_paths[0]);
}

static void return_multiple_values_too_many(void)
{
    format_test_name("semantics/statements/return/return_multiple_values_too_many");

    format_source_path(0, "semantics/statements/return/return_multiple_values_too_many.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b, I32 c, I32 d) : I32\n"
                          "    return b, c, d\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_multiple_values_too_many.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:15: 1 expression expected but found 3." NEW_LINE,
                       test.source_paths[0]);
}

static void return_non_retained_pointer(void)
{
    format_test_name("semantics/statements/return/return_non_retained_pointer");

    format_source_path(0, "semantics/statements/return/return_non_retained_pointer.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function do_stuff(#I32 a) : #`I32\n"
                          "    return a\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_non_retained_pointer.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:12: #`I32 expected but found #I32." NEW_LINE,
                       test.source_paths[0]);
}

static void return_one_too_few_values(void)
{
    format_test_name("semantics/statements/return/return_one_too_few_values");

    format_source_path(0, "semantics/statements/return/return_one_too_few_values.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b) : I32, I32\n"
                          "    return b\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_one_too_few_values.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:12: 2 expressions expected but found 1." NEW_LINE,
                       test.source_paths[0]);
}

static void return_one_too_many_values(void)
{
    format_test_name("semantics/statements/return/return_one_too_many_values");

    format_source_path(0, "semantics/statements/return/return_one_too_many_values.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b, I32 c) : I32\n"
                          "    return b, c\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_one_too_many_values.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:15: 1 expression expected but found 2." NEW_LINE,
                       test.source_paths[0]);
}

static void return_one_type_but_another_type_is_expected(void)
{
    format_test_name("semantics/statements/return/return_one_type_but_another_type_is_expected");

    format_source_path(0, "semantics/statements/return/return_one_type_but_another_type_is_expected.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration A : U8\n"
                          "   a \n"
                          "end\n"
                          "\n"
                          "enumeration B : U8\n"
                          "   b \n"
                          "end\n"
                          "\n"
                          "function a() : A\n"
                          "    return B.b\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_one_type_but_another_type_is_expected.owen");
    format_expectation(&test.expected_error, 
                       "%s:13:12: A expected but found B." NEW_LINE,
                       test.source_paths[0]);
}

static void return_the_multiple_expected_values_of_the_expected_types(void)
{
    format_test_name("semantics/statements/return/return_the_multiple_expected_values_of_the_expected_types");

    format_source_path(0, "semantics/statements/return/return_the_multiple_expected_values_of_the_expected_types.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function main(I32 a, F32 b) : I32, F32\n"
                          "    return a, b\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_the_multiple_expected_values_of_the_expected_types.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/return/return_the_multiple_expected_values_of_the_expected_types.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: F32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_type: F32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: a" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: F32" NEW_LINE
                       "                name: b" NEW_LINE);
}

static void return_the_one_expected_value_of_the_expected_type(void)
{
    format_test_name("semantics/statements/return/return_the_one_expected_value_of_the_expected_type");

    format_source_path(0, "semantics/statements/return/return_the_one_expected_value_of_the_expected_type.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b) : I32\n"
                          "    return b\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_the_one_expected_value_of_the_expected_type.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/return/return_the_one_expected_value_of_the_expected_type.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE);
}

static void return_the_right_amount_of_values_but_one_is_the_wrong_type(void)
{
    format_test_name("semantics/statements/return/return_the_right_amount_of_values_but_one_is_the_wrong_type");

    format_source_path(0, "semantics/statements/return/return_the_right_amount_of_values_but_one_is_the_wrong_type.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b, I32 c) : I32, U32\n"
                          "    return b, c\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_the_right_amount_of_values_but_one_is_the_wrong_type.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:15: U32 expected but found I32." NEW_LINE,
                       test.source_paths[0]);
}

static void return_values_when_no_return_types_are_declared(void)
{
    format_test_name("semantics/statements/return/return_values_when_no_return_types_are_declared");

    format_source_path(0, "semantics/statements/return/return_values_when_no_return_types_are_declared.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b)\n"
                          "    return b\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_values_when_no_return_types_are_declared.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:12: 0 expressions expected but found 1." NEW_LINE,
                       test.source_paths[0]);
}

static void return_no_values_when_return_types_are_declared(void)
{
    format_test_name("semantics/statements/return/return_no_values_when_return_types_are_declared");

    format_source_path(0, "semantics/statements/return/return_no_values_when_return_types_are_declared.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a() : I32\n"
                          "    return\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_no_values_when_return_types_are_declared.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:5: 1 expression expected but found 0." NEW_LINE,
                       test.source_paths[0]);
}

static void return_types_but_no_return_statement(void)
{
    format_test_name("semantics/statements/return/return_types_but_no_return_statement");

    format_source_path(0, "semantics/statements/return/return_types_but_no_return_statement.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a() : I32\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/return/return_types_but_no_return_statement.owen");
    format_expectation(&test.expected_error, 
                       "%s:4:10: Missing terminating statement." NEW_LINE,
                       test.source_paths[0]);
}

static bool return_x_type_compatible_literal(void)
{
    static uint8_t index = 0;
    while (true)
    {
        if (index == LAST_TYPE_INDEX)
            return false;

        bool is_valid_case = types[index].file_friendly_default_value_name != NULL;
        if (is_valid_case)
        {
            format_test_name("semantics/statements/return/return_%s_type_compatible_%s_typed_literal", types[index].file_friendly_name, types[index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure Structure\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "union Union\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "union Union[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "function a() : %s\n"
                                  "    return %s\n"
                                  "end", 
                                  types[index].name,
                                  types[index].default_value);

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            if (!strcmp("Structure[I32]", types[index].name))
            {
                format_expectation(&test.expected_semantics, 
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        actual_type_parameter: I32" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: a" NEW_LINE
                                   "        return_type: Structure[I32]" NEW_LINE
                                   "        return_statement" NEW_LINE
                                   "            compound_literal" NEW_LINE
                                   "                type: Structure[I32]" NEW_LINE
                                   "                field_initializer" NEW_LINE
                                   "                    type: I32" NEW_LINE
                                   "                    name: a" NEW_LINE
                                   "                    integer_literal" NEW_LINE
                                   "                        type: I32" NEW_LINE
                                   "                        value: 0" NEW_LINE,
                                   test.source_paths[0]);
            }
            else if (!strcmp("Union[I32]", types[index].name))
            {
                format_expectation(&test.expected_semantics, 
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        actual_type_parameter: I32" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: a" NEW_LINE
                                   "        return_type: Union[I32]" NEW_LINE
                                   "        return_statement" NEW_LINE
                                   "            compound_literal" NEW_LINE
                                   "                type: Union[I32]" NEW_LINE
                                   "                field_initializer" NEW_LINE
                                   "                    type: I32" NEW_LINE
                                   "                    name: a" NEW_LINE
                                   "                    integer_literal" NEW_LINE
                                   "                        type: I32" NEW_LINE
                                   "                        value: 0" NEW_LINE,
                                   test.source_paths[0]);
            }
            else if (types[index].default_value_name && !strcmp("Compound", types[index].default_value_name))
            {
                format_expectation(&test.expected_semantics, 
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: a" NEW_LINE
                                   "        return_type: %s" NEW_LINE
                                   "        return_statement" NEW_LINE
                                   "            compound_literal" NEW_LINE
                                   "                type: %s" NEW_LINE
                                   "                field_initializer" NEW_LINE
                                   "                    type: I32" NEW_LINE
                                   "                    name: a" NEW_LINE
                                   "                    integer_literal" NEW_LINE
                                   "                        type: I32" NEW_LINE
                                   "                        value: 0" NEW_LINE,
                                   test.source_paths[0],
                                   types[index].name,
                                   types[index].name);
            }
            else
            {
                format_expectation(&test.expected_semantics, 
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    structure" NEW_LINE
                                   "        name: Structure" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type: I32" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    union" NEW_LINE
                                   "        name: Union" NEW_LINE
                                   "        is_public: false" NEW_LINE
                                   "        formal_type_parameter: T" NEW_LINE
                                   "        field" NEW_LINE
                                   "            type_reference: T" NEW_LINE
                                   "            name: a" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: a" NEW_LINE
                                   "        return_type: %s" NEW_LINE
                                   "        return_statement" NEW_LINE
                                   "            %s_literal" NEW_LINE
                                   "                type: %s" NEW_LINE
                                   "                value: 0" NEW_LINE,
                                   test.source_paths[0],
                                   types[index].name,
                                   types[index].file_friendly_default_value_name,
                                   types[index].name);
            }
        }

        index++;
        if (is_valid_case)
            return true;
    }

    return false;
}

static bool return_x_type_incompatible_literal(void)
{
    static uint8_t lhs_index = 0;
    static uint8_t rhs_index = 0;

    while (true)
    {
        if (lhs_index == LAST_TYPE_INDEX)
            return false;

        bool is_valid_case = types[rhs_index].file_friendly_default_value_name &&
                             types[rhs_index].default_value_name &&
                             (!types[lhs_index].default_value_name || strcmp(types[lhs_index].default_value_name, types[rhs_index].default_value_name)) &&
                             (!rhs_index || (types[rhs_index - 1].default_value_name && strcmp(types[rhs_index].default_value_name, types[rhs_index - 1].default_value_name)));

        if (is_valid_case)
        {
            format_test_name("semantics/statements/return/return_%s_type_%s_literal", types[lhs_index].file_friendly_name, types[rhs_index].file_friendly_default_value_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "enumeration Enumeration : I32\n"
                                  "    a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "union Union\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "union Union[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "function a() : %s\n"
                                  "    return %s\n"
                                  "end", 
                                  types[lhs_index].name, 
                                  types[rhs_index].default_value);

            format_command_line_options("%s", test.source_paths[0]);
            format_expectation(&test.expected_error, 
                                "%s:25:12: Cannot infer literal as %s." NEW_LINE,
                                test.source_paths[0], 
                                types[lhs_index].name);
        }

        if (rhs_index == LAST_TYPE_INDEX)
        {
            rhs_index = 0;
            lhs_index++;
        }
        else
            rhs_index++;

        if (is_valid_case)
            return true;
    }

    return false;
}

static bool return_pointer_x_typed_expression_where_x_typed_expression_expected(void)
{
    static uint8_t expected_type_index = FIRST_POINTER_TYPE_INDEX;
    static uint8_t returned_type_index = FIRST_POINTER_TYPE_INDEX;

    if (expected_type_index > LAST_POINTER_TYPE_INDEX)
        return false;

    format_test_name("semantics/statements/return/return_%s_typed_expression_where_%s_typed_expression_expected", types[returned_type_index].file_friendly_name, types[expected_type_index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                            "namespace Abc\n"
                            "\n"
                            "function a(%s b) : %s\n"
                            "    return b\n"
                            "end", 
                            types[returned_type_index].name, types[expected_type_index].name);

    if (pointer_type_is_compatible_with(returned_type_index, expected_type_index))
    {
        format_command_line_options("%s -print-semantics", test.source_paths[0]);
        format_expectation(&test.expected_semantics, 
                            "file" NEW_LINE
                            "    path: %s" NEW_LINE
                            "    namespace: Abc" NEW_LINE
                            "    function" NEW_LINE
                            "        name: a" NEW_LINE
                            "        formal_parameter" NEW_LINE
                            "            type: %s" NEW_LINE
                            "            name: b" NEW_LINE
                            "        return_type: %s" NEW_LINE
                            "        return_statement" NEW_LINE
                            "            reference_expression" NEW_LINE
                            "                type: %s" NEW_LINE
                            "                name: b" NEW_LINE,
                            test.source_paths[0],
                            types[returned_type_index].name,
                            types[expected_type_index].name,
                            types[returned_type_index].name);
    }
    else
    {
        format_command_line_options("%s", test.source_paths[0]);
        format_expectation(&test.expected_error, 
                            "%s:5:12: %s expected but found %s." NEW_LINE,
                            test.source_paths[0],
                            types[expected_type_index].name, 
                            types[returned_type_index].name);
    }

    if (returned_type_index == LAST_POINTER_TYPE_INDEX)
    {
        returned_type_index = FIRST_POINTER_TYPE_INDEX;
        expected_type_index++;
    }
    else
        returned_type_index++;

    return true;
}

static bool x_typed_uninitialized_literal(void)
{    
    static uint8_t index = 0;
    if (index == TYPES_LENGTH)
        return false;

    format_test_name("semantics/statements/return/%s_typed_uninitialized_literal", types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function a() : %s\n"
                          "    return ---\n"
                          "end", 
                          types[index].name);

    format_command_line_options("%s -print-semantics", test.source_paths[0]);

    if (!strcmp("Union[I32]", types[index].name))
    {
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        actual_type_parameter: I32" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: a" NEW_LINE
                           "        return_type: Union[I32]" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            uninitialized_literal" NEW_LINE
                           "                type: Union[I32]" NEW_LINE,
                           test.source_paths[0]);
    }
    else if (!strcmp("Structure[I32]", types[index].name))
    {
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        actual_type_parameter: I32" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: a" NEW_LINE
                           "        return_type: Structure[I32]" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            uninitialized_literal" NEW_LINE
                           "                type: Structure[I32]" NEW_LINE,
                           test.source_paths[0]);
    }
    else
    {
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: a" NEW_LINE
                           "        return_type: %s" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            uninitialized_literal" NEW_LINE
                           "                type: %s" NEW_LINE,
                           test.source_paths[0],
                           types[index].name,
                           types[index].name);
    }

    index++;
    
    return true;
}

static bool dereferenced_return_value(void)
{
    static uint8_t type_index = 0;
    while (true)
    {
        if (type_index > LAST_TYPE_INDEX)
            return false;

        bool is_valid_case = type_index >= FIRST_POINTER_TYPE_INDEX && type_index <= LAST_POINTER_TYPE_INDEX;
        if (is_valid_case)
        {
            format_test_name("semantics/statements/return/dereferenced_%s_typed_return_value", types[type_index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(%s b) : I32\n"
                                  "    return @b\n"
                                  "end",
                                  types[type_index].name);

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            if (is_readable_type(type_index))
            {
                format_expectation(&test.expected_semantics,
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: a" NEW_LINE
                                   "        formal_parameter" NEW_LINE
                                   "            type: %s" NEW_LINE
                                   "            name: b" NEW_LINE
                                   "        return_type: I32" NEW_LINE
                                   "        return_statement" NEW_LINE
                                   "            dereference" NEW_LINE
                                   "                type: I32" NEW_LINE
                                   "                reference_expression" NEW_LINE
                                   "                    type: %s" NEW_LINE
                                   "                    name: b" NEW_LINE,
                                   test.source_paths[0],
                                   types[type_index].name,
                                   types[type_index].name);
            }
            else
            {
                format_expectation(&test.expected_error, 
                                   "%s:5:12: Missing readable privilege (?) from %s." NEW_LINE,
                                   test.source_paths[0],
                                   types[type_index].name);
            }
        }

        type_index++;
        if (is_valid_case)
            return true;
    }
}

static bool pointer_typed_field_access(void)
{
    static uint8_t state;
    switch (state++)
    {
        case 0:
            format_test_name("semantics/statements/return/field_access_to_pointer_readable_return_value");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "function a(#?A b) : I32\n"
                                  "    return b.a\n"
                                  "end");

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics,
                               "file" NEW_LINE
                               "    path: %s" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    structure" NEW_LINE
                               "        name: A" NEW_LINE
                               "        is_public: false" NEW_LINE
                               "        field" NEW_LINE
                               "            type: I32" NEW_LINE
                               "            name: a" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: #?A" NEW_LINE
                               "            name: b" NEW_LINE
                               "        return_type: I32" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            field_access" NEW_LINE
                               "                type: I32" NEW_LINE
                               "                reference_expression" NEW_LINE
                               "                    type: #?A" NEW_LINE
                               "                    name: b" NEW_LINE
                               "                field: a" NEW_LINE,
                               test.source_paths[0]);

            return true;
        
        case 1:
            format_test_name("semantics/statements/return/field_access_to_pointer_return_value");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "function a(#A b) : I32\n"
                                  "    return b.a\n"
                                  "end");

            format_command_line_options(test.source_paths[0]);
            format_expectation(&test.expected_error,
                               "%s:9:12: Missing readable privilege (?) from #A." NEW_LINE,
                               test.source_paths[0]);

            return true;

        default:
            return false;
    }
}

static bool pointer_typed_array_access(void)
{
    static uint8_t state;
    switch (state++)
    {
        case 0:
            format_test_name("semantics/statements/return/array_access_to_pointer_readable_return_value");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(#?[]I32 b) : I32\n"
                                  "    return b[0]\n"
                                  "end");

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics,
                               "file" NEW_LINE
                               "    path: %s" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: #?[]I32" NEW_LINE
                               "            name: b" NEW_LINE
                               "        return_type: I32" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            array_access" NEW_LINE
                               "                type: I32" NEW_LINE
                               "                reference_expression" NEW_LINE
                               "                    type: #?[]I32" NEW_LINE
                               "                    name: b" NEW_LINE
                               "                integer_literal" NEW_LINE
                               "                    type: U32" NEW_LINE
                               "                    value: 0" NEW_LINE,
                               test.source_paths[0]);

            return true;
        
        case 1:
            format_test_name("semantics/statements/return/array_access_to_pointer_return_value");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(#[]I32 b) : I32\n"
                                  "    return b[0]\n"
                                  "end");

            format_command_line_options(test.source_paths[0]);
            format_expectation(&test.expected_error,
                               "%s:5:12: Missing readable privilege (?) from #[]I32." NEW_LINE,
                               test.source_paths[0]);

            return true;

        default:
            return false;
    }
}

bool semantics_statements_return(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            polymorphic_and_monomorphic_return_types();
            state++;
            break;

        case 1:
            return_call_to_function_that_returns_multiple_values_matching_return_types();
            state++;
            break;

        case 2:
            return_call_to_function_that_returns_no_value();
            state++;
            break;

        case 3:
            return_multiple_values_too_few();
            state++;
            break;

        case 4:
            return_multiple_values_too_many();
            state++;
            break;

        case 5:
            return_non_retained_pointer();
            state++;
            break;

        case 6:
            return_one_too_few_values();
            state++;
            break;

        case 7:
            return_one_too_many_values();
            state++;
            break;

        case 8:
            return_one_type_but_another_type_is_expected();
            state++;
            break;

        case 9:
            return_the_multiple_expected_values_of_the_expected_types();
            state++;
            break;

        case 10:
            return_the_one_expected_value_of_the_expected_type();
            state++;
            break;

        case 11:
            return_the_right_amount_of_values_but_one_is_the_wrong_type();
            state++;
            break;

        case 12:
            return_values_when_no_return_types_are_declared();
            state++;
            break;

        case 13:
            return_no_values_when_return_types_are_declared();
            state++;
            break;

        case 14:
            return_types_but_no_return_statement();
            state++;
            break;

        case 15:
            if (return_x_type_compatible_literal())
                break;

            state++;

        case 16:
            if (return_x_type_incompatible_literal())
                break;

            state++;

        case 17:
            if (return_pointer_x_typed_expression_where_x_typed_expression_expected())
                break;

            state++;

        case 18:
            if (x_typed_uninitialized_literal())
                break;

            state++;

        case 19:
            if (dereferenced_return_value())
                break;

            state++;

        case 20:
            if (pointer_typed_field_access())
                break;

            state++;

        case 21:
            if (pointer_typed_array_access())
                break;

            state++;

        default:
            return false;
    }

    return true;
}
