#include "runner.h"

static bool x_typed_expression(void)
{    
    static uint8_t index = 0;
    if (index == TYPES_LENGTH)
        return false;

    format_test_name("semantics/expressions/negate/%s_typed_expression", types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function b(%s c) : %s\n"
                          "    return -c\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end", 
                          types[index].name,
                          types[index].name);

    if (index >= FIRST_SIGNED_NUMBER_TYPE_INDEX && index <= LAST_SIGNED_NUMBER_TYPE_INDEX || index >= FIRST_FLOAT_TYPE_INDEX && index <= LAST_FLOAT_TYPE_INDEX)
    {
        format_command_line_options("%s -print-semantics", test.source_paths[0]);
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: b" NEW_LINE
                           "        formal_parameter" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: c" NEW_LINE
                           "        return_type: %s" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            negate" NEW_LINE
                           "                type: %s" NEW_LINE
                           "                reference_expression" NEW_LINE
                           "                    type: %s" NEW_LINE
                           "                    name: c" NEW_LINE
                           "    function" NEW_LINE
                           "        name: main" NEW_LINE
                           "        return_type: I32" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            integer_literal" NEW_LINE
                           "                type: I32" NEW_LINE
                           "                value: 0" NEW_LINE,
                           test.source_paths[0],
                           types[index].name,
                           types[index].name,
                           types[index].name,
                           types[index].name);
    }
    else
    {
        format_command_line_options(test.source_paths[0]);
        format_expectation(&test.expected_error, 
                           "%s:25:13: Operator not defined for %s." NEW_LINE,
                           test.source_paths[0],
                           types[index].name);
    }

    index++;
    
    return true;
}

static bool x_typed_literal(void)
{    
    static uint8_t index = 0;
    while (true)
    {
        if (index == TYPES_LENGTH)
            return false;

        bool is_valid_case = index >= FIRST_SIGNED_NUMBER_TYPE_INDEX && index <= LAST_SIGNED_NUMBER_TYPE_INDEX || index >= FIRST_FLOAT_TYPE_INDEX && index <= LAST_FLOAT_TYPE_INDEX;
        if (is_valid_case)
        {
            format_test_name("semantics/expressions/negate/%s_typed_literal", types[index].file_friendly_name);
            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function b() : %s\n"
                                  "    return -%s\n"
                                  "end\n"
                                  "\n"
                                  "function main() : I32\n"
                                  "    return 0\n"
                                  "end",
                                  types[index].name,
                                  index >= FIRST_FLOAT_TYPE_INDEX && index <= LAST_FLOAT_TYPE_INDEX ? "1.0" : "1");

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics, 
                               "file" NEW_LINE
                               "    path: %s" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    function" NEW_LINE
                               "        name: b" NEW_LINE
                               "        return_type: %s" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            %s_literal" NEW_LINE
                               "                type: %s" NEW_LINE
                               "                value: -1" NEW_LINE
                               "    function" NEW_LINE
                               "        name: main" NEW_LINE
                               "        return_type: I32" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            integer_literal" NEW_LINE
                               "                type: I32" NEW_LINE
                               "                value: 0" NEW_LINE,
                               test.source_paths[0],
                               types[index].name,
                               types[index].file_friendly_default_value_name,
                               types[index].name);
        }

        index++;
        if (is_valid_case)
            break;
    }
    
    return true;
}

bool semantics_expressions_negate(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            if (x_typed_expression())
                break;

            state++;

        case 1:
            if (x_typed_literal())
                break;

            state++;

        default:
            return false;
    }

    return true;
}
