#include "runner.h"

static bool sizeof_x_typed_expression(void)
{
    static uint8_t index = 0;
    if (index == LAST_TYPE_INDEX)
        return false;

    format_test_name("semantics/expressions/sizeof/sizeof_%s_typed_expression", types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function a(%s b) : I32\n"
                          "    return sizeof(b)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end",
                          types[index].name);

    format_command_line_options("%s -print-semantics", test.source_paths[0]);
    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: %s" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    enumeration" NEW_LINE
                       "        name: Enumeration" NEW_LINE
                       "        underlying_type: I32" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        constant" NEW_LINE
                       "            name: a" NEW_LINE
                       "            value: 0" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: Structure" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: a" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: Structure" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        field" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: a" NEW_LINE
                       "    union" NEW_LINE
                       "        name: Union" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: a" NEW_LINE
                       "    union" NEW_LINE
                       "        name: Union" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        field" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: a" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: %s" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: %u" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE,
                       test.source_paths[0],
                       types[index].name,
                       types[index].size_of);

    index++;
    return true;
}

static bool sizeof_x_type(void)
{
    static uint8_t index = 0;
    if (index == LAST_TYPE_INDEX)
        return false;

    format_test_name("semantics/expressions/sizeof/sizeof_%s_type", types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function a() : I32\n"
                          "    return sizeof(%s)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end",
                          types[index].name);

    format_command_line_options("%s -print-semantics", test.source_paths[0]);
    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: %s" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    enumeration" NEW_LINE
                       "        name: Enumeration" NEW_LINE
                       "        underlying_type: I32" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        constant" NEW_LINE
                       "            name: a" NEW_LINE
                       "            value: 0" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: Structure" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: a" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: Structure" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        field" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: a" NEW_LINE
                       "    union" NEW_LINE
                       "        name: Union" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: a" NEW_LINE
                       "    union" NEW_LINE
                       "        name: Union" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        field" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: a" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: %u" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE,
                       test.source_paths[0],
                       types[index].size_of);

    index++;
    return true;
}

bool semantics_expressions_sizeof(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            if (sizeof_x_typed_expression())
                break;
            
            state++;

        case 1:
            if (sizeof_x_type())
                break;

            state++;

        default:
            return false;
    }

    return true;
}
