#include "runner.h"

static void bool_typed_condition(void)
{
    format_test_name("semantics/statements/while/bool_typed_condition");

    format_source_path(0, "semantics/statements/while/bool_typed_condition.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(Bool b)\n"
                          "    while b\n"
                          "    end\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/while/bool_typed_condition.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/while/bool_typed_condition.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: Bool" NEW_LINE
                       "            name: b" NEW_LINE
                       "        loop_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Bool" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void monomorphic_statement_in_a_polymorphic_function(void)
{
    format_test_name("semantics/statements/while/monomorphic_statement_in_a_polymorphic_function");

    format_source_path(0, "semantics/statements/while/monomorphic_statement_in_a_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]()\n"
                          "    while I32 b = 0; b != 0\n"
                          "        b = 0\n"
                          "    end\n"
                          "end\n"
                          "\n"
                          "function c()\n"
                          "    a[U8]()\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/while/monomorphic_statement_in_a_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/while/monomorphic_statement_in_a_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        loop_statement" NEW_LINE
                       "            declaration_statement" NEW_LINE
                       "                variable" NEW_LINE
                       "                    type_reference: I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "            binary" NEW_LINE
                       "                operator: !=" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "            assignment_statement" NEW_LINE
                       "                operator: =" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: U8" NEW_LINE
                       "        loop_statement" NEW_LINE
                       "            declaration_statement" NEW_LINE
                       "                variable" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "            binary" NEW_LINE
                       "                type: Bool" NEW_LINE
                       "                operator: !=" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "            assignment_statement" NEW_LINE
                       "                operator: =" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        call_expression" NEW_LINE
                       "            type: none" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Function()" NEW_LINE
                       "                name: a" NEW_LINE
                       "                actual_type_parameter: U8" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static bool non_bool_typed_condition(void)
{
    static uint8_t index = 0;
    while (true)
    {
        if (index == LAST_TYPE_INDEX)
            return false;

        bool is_valid_case = strcmp("Bool", types[index].name);
        if (is_valid_case)
        {
            format_test_name("semantics/statements/while/%s_typed_condition", types[index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "enumeration Enumeration : I32\n"
                                  "    a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "structure Structure[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "union Union\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "union Union[T]\n"
                                  "    T a\n"
                                  "end\n"
                                  "\n"
                                  "function a(%s b)\n"
                                  "    while b\n"
                                  "    end\n"
                                  "end", 
                                  types[index].name);

            format_command_line_options(test.source_paths[0]);
            format_expectation(&test.expected_error, 
                               "%s:25:11: Bool expected but found %s." NEW_LINE,
                               test.source_paths[0], 
                               types[index].name);
        }

        index++;
        if (is_valid_case)
            return true;
    }

    return false;
}

static void polymorphic_statement_in_a_polymorphic_function(void)
{
    format_test_name("semantics/statements/while/polymorphic_statement_in_a_polymorphic_function");

    format_source_path(0, "semantics/statements/while/polymorphic_statement_in_a_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]()\n"
                          "    while T b = 0; b != 0\n"
                          "        b = 0"
                          "    end\n"
                          "end\n"
                          "\n"
                          "function c()\n"
                          "    a[U8]()\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/while/polymorphic_statement_in_a_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/while/polymorphic_statement_in_a_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        loop_statement" NEW_LINE
                       "            declaration_statement" NEW_LINE
                       "                variable" NEW_LINE
                       "                    type_reference: T" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "            binary" NEW_LINE
                       "                operator: !=" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "            assignment_statement" NEW_LINE
                       "                operator: =" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: U8" NEW_LINE
                       "        loop_statement" NEW_LINE
                       "            declaration_statement" NEW_LINE
                       "                variable" NEW_LINE
                       "                    type: U8" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: U8" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "            binary" NEW_LINE
                       "                type: Bool" NEW_LINE
                       "                operator: !=" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: U8" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: U8" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "            assignment_statement" NEW_LINE
                       "                operator: =" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: U8" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: U8" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        call_expression" NEW_LINE
                       "            type: none" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Function()" NEW_LINE
                       "                name: a" NEW_LINE
                       "                actual_type_parameter: U8" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void redeclare_variable_declared_before_body(void)
{
    format_test_name("semantics/statements/while/redeclare_variable_declared_before_body");

    format_source_path(0, "semantics/statements/while/redeclare_variable_declared_before_body.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function main()\n"
                          "    while I32 b = 0; false\n"
                          "        I32 b = 42\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/while/redeclare_variable_declared_before_body.owen");

    format_expectation(&test.expected_error, 
                       "%s:6:13: b is already defined." NEW_LINE,
                       test.source_paths[0]);
}

static void redeclare_variable_declared_in_the_outer_scope(void)
{
    format_test_name("semantics/statements/while/redeclare_variable_declared_in_the_outer_scope");

    format_source_path(0, "semantics/statements/while/redeclare_variable_declared_in_the_outer_scope.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    I32 b = 0\n"
                          "    \n"
                          "    while false\n"
                          "        I32 b = 42\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/while/redeclare_variable_declared_in_the_outer_scope.owen");

    format_expectation(&test.expected_error, 
                       "%s:8:13: b is already defined." NEW_LINE,
                       test.source_paths[0]);
}

static void refer_to_variable_declared_before_body_in_the_inner_scope(void)
{
    format_test_name("semantics/statements/while/refer_to_variable_declared_before_body_in_the_inner_scope");

    format_source_path(0, "semantics/statements/while/refer_to_variable_declared_before_body_in_the_inner_scope.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function main() : I32\n"
                          "    while I32 b = 0; false\n"
                          "        b = b\n"
                          "    end\n"
                          "\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/while/refer_to_variable_declared_before_body_in_the_inner_scope.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/while/refer_to_variable_declared_before_body_in_the_inner_scope.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        loop_statement" NEW_LINE
                       "            declaration_statement" NEW_LINE
                       "                variable" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "            boolean_literal" NEW_LINE
                       "                type: Bool" NEW_LINE
                       "                value: false" NEW_LINE
                       "            assignment_statement" NEW_LINE
                       "                operator: =" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void refer_to_variable_declared_in_body_in_the_inner_scope(void)
{
    format_test_name("semantics/statements/while/refer_to_variable_declared_in_body_in_the_inner_scope");

    format_source_path(0, "semantics/statements/while/refer_to_variable_declared_in_body_in_the_inner_scope.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function main() : I32\n"
                          "    while false\n"
                          "        I32 b = 0\n"
                          "        b = b\n"
                          "    end\n"
                          "\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/while/refer_to_variable_declared_in_body_in_the_inner_scope.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/while/refer_to_variable_declared_in_body_in_the_inner_scope.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        loop_statement" NEW_LINE
                       "            boolean_literal" NEW_LINE
                       "                type: Bool" NEW_LINE
                       "                value: false" NEW_LINE
                       "            declaration_statement" NEW_LINE
                       "                variable" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "            assignment_statement" NEW_LINE
                       "                operator: =" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void refer_to_variable_declared_in_the_outer_scope_inside_inner_scope(void)
{
    format_test_name("semantics/statements/while/refer_to_variable_declared_in_the_outer_scope_inside_inner_scope");

    format_source_path(0, "semantics/statements/while/refer_to_variable_declared_in_the_outer_scope_inside_inner_scope.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function main() : I32\n"
                          "    I32 a = 0\n"
                          "    \n"
                          "    while false\n"
                          "        a = a\n"
                          "    end\n"
                          "\n"\
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/while/refer_to_variable_declared_in_the_outer_scope_inside_inner_scope.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/while/refer_to_variable_declared_in_the_outer_scope_inside_inner_scope.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        declaration_statement" NEW_LINE
                       "            variable" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: a" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE
                       "        loop_statement" NEW_LINE
                       "            boolean_literal" NEW_LINE
                       "                type: Bool" NEW_LINE
                       "                value: false" NEW_LINE
                       "            assignment_statement" NEW_LINE
                       "                operator: =" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void unused_variable_declared_before_body(void)
{
    format_test_name("semantics/statements/while/unused_variable_declared_before_body");

    format_source_path(0, "semantics/statements/while/unused_variable_declared_before_body.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    while I32 b = 0; false\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/while/unused_variable_declared_before_body.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:15: Unused variable." NEW_LINE,
                       test.source_paths[0]);
}

static void unused_variable_declared_in_body(void)
{
    format_test_name("semantics/statements/while/unused_variable_declared_in_body");

    format_source_path(0, "semantics/statements/while/unused_variable_declared_in_body.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    while false\n"
                          "        I32 b = 0\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/while/unused_variable_declared_in_body.owen");
    format_expectation(&test.expected_error, 
                       "%s:6:13: Unused variable." NEW_LINE,
                       test.source_paths[0]);
}

static bool dereferenced_condition(void)
{
    static uint8_t type_index = 0;
    while (true)
    {
        if (type_index > LAST_TYPE_INDEX)
            return false;

        bool is_valid_case = type_index >= FIRST_POINTER_TYPE_INDEX && type_index <= LAST_POINTER_TYPE_INDEX;
        if (is_valid_case)
        {
            format_test_name("semantics/statements/while/dereferenced_%s_typed_condition", types[type_index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(%s b)\n"
                                  "    while @b == 1\n"
                                  "    end\n"
                                  "end\n"
                                  "\n"
                                  "function main() : I32\n"
                                  "    return 0\n"
                                  "end",
                                  types[type_index].name);

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            if (is_readable_type(type_index))
            {
                format_expectation(&test.expected_semantics,
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: a" NEW_LINE
                                   "        formal_parameter" NEW_LINE
                                   "            type: %s" NEW_LINE
                                   "            name: b" NEW_LINE
                                   "        loop_statement" NEW_LINE
                                   "            binary" NEW_LINE
                                   "                type: Bool" NEW_LINE
                                   "                operator: ==" NEW_LINE
                                   "                dereference" NEW_LINE
                                   "                    type: I32" NEW_LINE
                                   "                    reference_expression" NEW_LINE
                                   "                        type: %s" NEW_LINE
                                   "                        name: b" NEW_LINE
                                   "                integer_literal" NEW_LINE
                                   "                    type: I32" NEW_LINE
                                   "                    value: 1" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: main" NEW_LINE
                                   "        return_type: I32" NEW_LINE
                                   "        return_statement" NEW_LINE
                                   "            integer_literal" NEW_LINE
                                   "                type: I32" NEW_LINE
                                   "                value: 0" NEW_LINE,
                                   test.source_paths[0],
                                   types[type_index].name,
                                   types[type_index].name);
            }
            else
            {
                format_expectation(&test.expected_error, 
                                   "%s:5:11: Missing readable privilege (?) from %s." NEW_LINE,
                                   test.source_paths[0],
                                   types[type_index].name);
            }
        }

        type_index++;
        if (is_valid_case)
            return true;
    }
}

static bool pointer_typed_field_access(void)
{
    static uint8_t state;
    switch (state++)
    {
        case 0:
            format_test_name("semantics/statements/while/field_access_to_pointer_readable_condition");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "function a(#?A b)\n"
                                  "    while b.a == 1\n"
                                  "    end\n"
                                  "end\n"
                                  "\n"
                                  "function main() : I32\n"
                                  "    return 0\n"
                                  "end");

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics,
                               "file" NEW_LINE
                               "    path: %s" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    structure" NEW_LINE
                               "        name: A" NEW_LINE
                               "        is_public: false" NEW_LINE
                               "        field" NEW_LINE
                               "            type: I32" NEW_LINE
                               "            name: a" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: #?A" NEW_LINE
                               "            name: b" NEW_LINE
                               "        loop_statement" NEW_LINE
                               "            binary" NEW_LINE
                               "                type: Bool" NEW_LINE
                               "                operator: ==" NEW_LINE
                               "                field_access" NEW_LINE
                               "                    type: I32" NEW_LINE
                               "                    reference_expression" NEW_LINE
                               "                        type: #?A" NEW_LINE
                               "                        name: b" NEW_LINE
                               "                    field: a" NEW_LINE
                               "                integer_literal" NEW_LINE
                               "                    type: I32" NEW_LINE
                               "                    value: 1" NEW_LINE
                               "    function" NEW_LINE
                               "        name: main" NEW_LINE
                               "        return_type: I32" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            integer_literal" NEW_LINE
                               "                type: I32" NEW_LINE
                               "                value: 0" NEW_LINE,
                               test.source_paths[0]);

            return true;
        
        case 1:
            format_test_name("semantics/statements/while/field_access_to_pointer_condition");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "function a(#A b)\n"
                                  "    while b.a == 1\n"
                                  "    end\n"
                                  "end");

            format_command_line_options(test.source_paths[0]);
            format_expectation(&test.expected_error,
                               "%s:9:11: Missing readable privilege (?) from #A." NEW_LINE,
                               test.source_paths[0]);

            return true;

        default:
            return false;
    }
}

static bool pointer_typed_array_access(void)
{
    static uint8_t state;
    switch (state++)
    {
        case 0:
            format_test_name("semantics/statements/while/array_access_to_pointer_readable_condition");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(#?[]I32 b)\n"
                                  "    while b[0] == 1\n"
                                  "    end\n"
                                  "end\n"
                                  "\n"
                                  "function main() : I32\n"
                                  "    return 0\n"
                                  "end");

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics,
                               "file" NEW_LINE
                               "    path: %s" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: #?[]I32" NEW_LINE
                               "            name: b" NEW_LINE
                               "        loop_statement" NEW_LINE
                               "            binary" NEW_LINE
                               "                type: Bool" NEW_LINE
                               "                operator: ==" NEW_LINE
                               "                array_access" NEW_LINE
                               "                    type: I32" NEW_LINE
                               "                    reference_expression" NEW_LINE
                               "                        type: #?[]I32" NEW_LINE
                               "                        name: b" NEW_LINE
                               "                    integer_literal" NEW_LINE
                               "                        type: U32" NEW_LINE
                               "                        value: 0" NEW_LINE
                               "                integer_literal" NEW_LINE
                               "                    type: I32" NEW_LINE
                               "                    value: 1" NEW_LINE
                               "    function" NEW_LINE
                               "        name: main" NEW_LINE
                               "        return_type: I32" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            integer_literal" NEW_LINE
                               "                type: I32" NEW_LINE
                               "                value: 0" NEW_LINE,
                               test.source_paths[0]);

            return true;
        
        case 1:
            format_test_name("semantics/statements/while/array_access_to_pointer_condition");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(#[]I32 b)\n"
                                  "    while b[0] == 1\n"
                                  "    end\n"
                                  "end");

            format_command_line_options(test.source_paths[0]);
            format_expectation(&test.expected_error,
                               "%s:5:11: Missing readable privilege (?) from #[]I32." NEW_LINE,
                               test.source_paths[0]);

            return true;

        default:
            return false;
    }
}

bool semantics_statements_while(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            bool_typed_condition();
            state++;
            break;

        case 1:
            monomorphic_statement_in_a_polymorphic_function();
            state++;
            break;

        case 2:
            if (non_bool_typed_condition())
                break;

            state++;

        case 3:
            polymorphic_statement_in_a_polymorphic_function();
            state++;
            break;

        case 4:
            redeclare_variable_declared_before_body();
            state++;
            break;

        case 5:
            redeclare_variable_declared_in_the_outer_scope();
            state++;
            break;

        case 6:
            refer_to_variable_declared_before_body_in_the_inner_scope();
            state++;
            break;

        case 7:
            refer_to_variable_declared_in_body_in_the_inner_scope();
            state++;
            break;

        case 8:
            refer_to_variable_declared_in_the_outer_scope_inside_inner_scope();
            state++;
            break;

        case 9:
            unused_variable_declared_before_body();
            state++;
            break;

        case 10:
            unused_variable_declared_in_body();
            state++;
            break;

        case 11:
            if (dereferenced_condition())
                break;

            state++;

        case 12:
            if (pointer_typed_field_access())
                break;

            state++;

        case 13:
            if (pointer_typed_array_access())
                break;

            state++;

        default:
            return false;
    }

    return true;
}
