#include "runner.h"

static void call_reference_that_is_not_a_function(void)
{
    format_test_name("semantics/expressions/call/monomorphic/call_reference_that_is_not_a_function");

    format_source_path(0, "semantics/expressions/call/monomorphic/call_reference_that_is_not_a_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b)\n"
                          "    b()\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/monomorphic/call_reference_that_is_not_a_function.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:5: Function type expected but found I32." NEW_LINE,
                       test.source_paths[0]);
}

static void call_to_function_with_multiple_actual_parameters_matching_multiple_formal_parameters(void)
{
    format_test_name("semantics/expressions/call/monomorphic/call_to_function_with_multiple_actual_parameters_matching_multiple_formal_parameters");

    format_source_path(0, "semantics/expressions/call/monomorphic/call_to_function_with_multiple_actual_parameters_matching_multiple_formal_parameters.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b) : I32, I32\n"
                          "    return b, b\n"
                          "end\n"
                          "\n"
                          "function c(I32 d)\n"
                          "    d, d = a(d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/monomorphic/call_to_function_with_multiple_actual_parameters_matching_multiple_formal_parameters.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/monomorphic/call_to_function_with_multiple_actual_parameters_matching_multiple_formal_parameters.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        assignment_statement" NEW_LINE
                       "            operator: =" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: d" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: d" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32, I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32) : I32, I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void call_to_function_with_multiple_actual_parameters_matching_the_formal_parameters(void)
{
    format_test_name("semantics/expressions/call/monomorphic/call_to_function_with_multiple_actual_parameters_matching_the_formal_parameters");

    format_source_path(0, "semantics/expressions/call/monomorphic/call_to_function_with_multiple_actual_parameters_matching_the_formal_parameters.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b, I32 c) : I32, I32\n"
                          "    return b, c\n"
                          "end\n"
                          "\n"
                          "function d(I32 e)\n"
                          "    e, e = a(e, e)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/monomorphic/call_to_function_with_multiple_actual_parameters_matching_the_formal_parameters.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/monomorphic/call_to_function_with_multiple_actual_parameters_matching_the_formal_parameters.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: c" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: c" NEW_LINE
                       "    function" NEW_LINE
                       "        name: d" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: e" NEW_LINE
                       "        assignment_statement" NEW_LINE
                       "            operator: =" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: e" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: e" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32, I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32, I32) : I32, I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: e" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: e" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void call_to_function_with_one_actual_parameter_matching_one_formal_parameter(void)
{
    format_test_name("semantics/expressions/call/monomorphic/call_to_function_with_one_actual_parameter_matching_one_formal_parameter");

    format_source_path(0, "semantics/expressions/call/monomorphic/call_to_function_with_one_actual_parameter_matching_one_formal_parameter.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b) : I32\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(I32 d) : I32\n" 
                          "    return a(d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/monomorphic/call_to_function_with_one_actual_parameter_matching_one_formal_parameter.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/monomorphic/call_to_function_with_one_actual_parameter_matching_one_formal_parameter.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void call_to_function_with_zero_actual_parameters_matching_zero_formal_parameters(void)
{
    format_test_name("semantics/expressions/call/monomorphic/call_to_function_with_zero_actual_parameters_matching_zero_formal_parameters");

    format_source_path(0, "semantics/expressions/call/monomorphic/call_to_function_with_zero_actual_parameters_matching_zero_formal_parameters.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "end\n"
                          "\n"
                          "function b()\n"
                          "    a()\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/monomorphic/call_to_function_with_zero_actual_parameters_matching_zero_formal_parameters.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/monomorphic/call_to_function_with_zero_actual_parameters_matching_zero_formal_parameters.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "    function" NEW_LINE
                       "        name: b" NEW_LINE
                       "        call_expression" NEW_LINE
                       "            type: none" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Function()" NEW_LINE
                       "                name: a" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE );
}

static void call_undefined_function(void)
{
    format_test_name("semantics/expressions/call/monomorphic/call_undefined_function");

    format_source_path(0, "semantics/expressions/call/monomorphic/call_undefined_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    b()\n"
                          "end\n");

    SET_COMMAND_LINE("semantics/expressions/call/monomorphic/call_undefined_function.owen");

    format_expectation(&test.expected_error, 
                       "%s:5:5: b is undefined." NEW_LINE,
                       test.source_paths[0]);
}

static bool literal_as_actual_parameter(void)
{
    static uint8_t index = 0;
    while (index < TYPES_LENGTH && !types[index].default_value_name)
        index++;

    if (index == TYPES_LENGTH)
        return false;

    format_test_name("semantics/expressions/call/monomorphic/%s_literal_where_%s_typed_actual_parameter_expected", types[index].file_friendly_default_value_name, types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function a(%s b) : %s\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c()\n"
                          "    a(%s)\n"
                          "end", 
                          types[index].name, types[index].name,
                          types[index].default_value);

    format_command_line_options("%s", test.source_paths[0]);
    format_expectation(&test.expected_error, 
                       "%s:25:7: %s type cannot be inferred." NEW_LINE,
                       test.source_paths[0],
                       types[index].default_value_name);

    index++;
    return true;
}

static bool pass_x_typed_expression_to_compatible_formal_parameter(void)
{
    static uint8_t lhs_index = FIRST_POINTER_TYPE_INDEX;
    static uint8_t rhs_index = FIRST_POINTER_TYPE_INDEX;

    while (true)
    {
        if (lhs_index > LAST_POINTER_TYPE_INDEX)
            return false;

        bool is_valid_case = pointer_type_is_compatible_with(lhs_index, rhs_index) &&
                             pointer_is_retained(lhs_index) && 
                             pointer_is_retained(rhs_index);

        if (is_valid_case)
        {
            format_test_name("semantics/expressions/call/monomorphic/pass_%s_typed_expression_to_%s_typed_formal_parameter", types[lhs_index].file_friendly_name, types[rhs_index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(%s b) : %s\n"
                                  "    return b\n"
                                  "end\n"
                                  "\n"
                                  "function c(%s d) : %s\n"
                                  "    return a(d)\n"
                                  "end\n"
                                  "\n"
                                  "function main() : I32\n"
                                  "    return 0\n"
                                  "end", 
                                  types[rhs_index].name, types[rhs_index].name,
                                  types[lhs_index].name, types[rhs_index].name);

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics, 
                               "file" NEW_LINE
                               "    path: %s" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: %s" NEW_LINE
                               "            name: b" NEW_LINE
                               "        return_type: %s" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            reference_expression" NEW_LINE
                               "                type: %s" NEW_LINE
                               "                name: b" NEW_LINE
                               "    function" NEW_LINE
                               "        name: c" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: %s" NEW_LINE
                               "            name: d" NEW_LINE
                               "        return_type: %s" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            call_expression" NEW_LINE
                               "                type: %s" NEW_LINE
                               "                reference_expression" NEW_LINE
                               "                    type: Function(%s) : %s" NEW_LINE
                               "                    name: a" NEW_LINE
                               "                reference_expression" NEW_LINE
                               "                    type: %s" NEW_LINE
                               "                    name: d" NEW_LINE
                               "    function" NEW_LINE
                               "        name: main" NEW_LINE
                               "        return_type: I32" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            integer_literal" NEW_LINE
                               "                type: I32" NEW_LINE
                               "                value: 0" NEW_LINE,
                               test.source_paths[0],
                               types[rhs_index].name,
                               types[rhs_index].name,
                               types[rhs_index].name,
                               types[lhs_index].name,
                               types[rhs_index].name,
                               types[rhs_index].name,
                               types[rhs_index].name, types[rhs_index].name,
                               types[lhs_index].name);
        }

        if (rhs_index > LAST_POINTER_TYPE_INDEX)
        {
            rhs_index = FIRST_POINTER_TYPE_INDEX;
            lhs_index++;
        }
        else
            rhs_index++;

        if (is_valid_case)
            return true;
    }

    return false;
}

static bool pass_x_typed_expression_to_incompatible_formal_parameter(void)
{
    static uint8_t lhs_index = FIRST_POINTER_TYPE_INDEX;
    static uint8_t rhs_index = FIRST_POINTER_TYPE_INDEX;

    while (true)
    {
        if (lhs_index > LAST_POINTER_TYPE_INDEX)
            return false;

        bool is_valid_case = !pointer_type_is_compatible_with(lhs_index, rhs_index) &&
                              pointer_is_retained(lhs_index) && 
                              pointer_is_retained(rhs_index);

        if (is_valid_case)
        {
            format_test_name("semantics/expressions/call/monomorphic/pass_%s_typed_expression_to_%s_typed_formal_parameter", types[lhs_index].file_friendly_name, types[rhs_index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(%s b) : %s\n"
                                  "    return b\n"
                                  "end\n"
                                  "\n"
                                  "function c(%s d) : %s\n"
                                  "    return a(d)\n"
                                  "end", 
                                  types[rhs_index].name, types[rhs_index].name,
                                  types[lhs_index].name, types[rhs_index].name);

            format_command_line_options(test.source_paths[0]);
            format_expectation(&test.expected_error, 
                               "%s:9:12: No matching signature for a." NEW_LINE
                               "Declarations:"NEW_LINE
                               "    %s:4:10: a(%s b) : %s" NEW_LINE,
                               test.source_paths[0],
                               test.source_paths[0],
                               types[rhs_index].name, 
                               types[rhs_index].name);
        }

        if (rhs_index > LAST_POINTER_TYPE_INDEX)
        {
            rhs_index = FIRST_POINTER_TYPE_INDEX;
            lhs_index++;
        }
        else
            rhs_index++;

        if (is_valid_case)
            return true;
    }

    return false;
}

bool semantics_expressions_call_monomorphic(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            call_reference_that_is_not_a_function();
            state++;
            break;

        case 1:
            call_to_function_with_multiple_actual_parameters_matching_multiple_formal_parameters();
            state++;
            break;

        case 2:
            call_to_function_with_multiple_actual_parameters_matching_the_formal_parameters();
            state++;
            break;

        case 3:
            call_to_function_with_one_actual_parameter_matching_one_formal_parameter();
            state++;
            break;

        case 4:
            call_to_function_with_zero_actual_parameters_matching_zero_formal_parameters();
            state++;
            break;

        case 5:
            call_undefined_function();
            state++;
            break;

        case 6:
            if (literal_as_actual_parameter())
                break;

            state++;

        case 7:
            if (pass_x_typed_expression_to_compatible_formal_parameter())
                break;

            state++;

        case 8:
            if (pass_x_typed_expression_to_incompatible_formal_parameter())
                break;

            state++;

        default:
            return false;
    }

    return true;
}
