#include "runner.h"

static void no_parameters_or_return_types(void)
{
    format_test_name("semantics/expressions/call/function_typed/no_parameters_or_return_types");

    format_source_path(0, "semantics/expressions/call/function_typed/no_parameters_or_return_types.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(Function() b)\n"
                          "    b()\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/function_typed/no_parameters_or_return_types.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/function_typed/no_parameters_or_return_types.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: Function()" NEW_LINE
                       "            name: b" NEW_LINE
                       "        call_expression" NEW_LINE
                       "            type: none" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Function()" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void matching_number_of_parameters_but_wrong_type(void)
{
    format_test_name("semantics/expressions/call/function_typed/matching_number_of_parameters_but_wrong_type");

    format_source_path(0, "semantics/expressions/call/function_typed/matching_number_of_parameters_but_wrong_type.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(Function(I8) b, I32 c)\n"
                          "    b(c)\n"
                          "end\n");

    SET_COMMAND_LINE("semantics/expressions/call/function_typed/matching_number_of_parameters_but_wrong_type.owen");

    format_expectation(&test.expected_error, 
                       "%s:5:7: I8 expected but found I32." NEW_LINE,
                       test.source_paths[0]);
}

static void matching_number_of_parameters_and_types(void)
{
    format_test_name("semantics/expressions/call/function_typed/matching_number_of_parameters_and_types");

    format_source_path(0, "semantics/expressions/call/function_typed/matching_number_of_parameters_and_types.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(Function(I32) b, I32 c)\n"
                          "    b(c)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/function_typed/matching_number_of_parameters_and_types.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/function_typed/matching_number_of_parameters_and_types.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: Function(I32)" NEW_LINE
                       "            name: b" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: c" NEW_LINE
                       "        call_expression" NEW_LINE
                       "            type: none" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Function(I32)" NEW_LINE
                       "                name: b" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: c" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

bool semantics_expressions_call_function_typed(void)
{
    static uint8_t state;
    switch (state++)
    {
        case 0:
            no_parameters_or_return_types();
            break;

        case 1:
            matching_number_of_parameters_but_wrong_type();
            break;

        case 2:
            matching_number_of_parameters_and_types();
            break;

        default:
            return false;
    }

    return true;
}
