#include "runner.h"

static bool x_typed_condition(void)
{
    static uint8_t index = 0;
    if (index == LAST_TYPE_INDEX)
        return false;

    format_test_name("semantics/statements/if/%s_typed_condition", types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function a(%s b)\n"
                          "    if b\n"
                          "    end\n"
                          "end", 
                          types[index].name);

    format_command_line_options("%s -print-semantics", test.source_paths[0]);
    if (strcmp("Bool", types[index].name))
    {
        format_expectation(&test.expected_error, 
                           "%s:25:8: Bool expected but found %s." NEW_LINE,
                           test.source_paths[0], 
                           types[index].name);
    }
    else
    {
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: a" NEW_LINE
                           "        formal_parameter" NEW_LINE
                           "            type: %s" NEW_LINE
                           "            name: b" NEW_LINE
                           "        if_statement" NEW_LINE
                           "            branch" NEW_LINE
                           "                reference_expression" NEW_LINE
                           "                    type: %s" NEW_LINE
                           "                    name: b" NEW_LINE,
                           test.source_paths[0],
                           types[index].name,
                           types[index].name);
    }

    index++;

    return true;
}

static void monomorphic_statement_in_a_polymorphic_function(void)
{
    format_test_name("semantics/statements/if/monomorphic_statement_in_a_polymorphic_function");

    format_source_path(0, "semantics/statements/if/monomorphic_statement_in_a_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]()\n"
                          "    if I32 b = 0; b != 0\n"
                          "        b = 0\n"
                          "    end\n"
                          "end\n"
                          "\n"
                          "function c()\n"
                          "    a[U8]()\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/monomorphic_statement_in_a_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/if/monomorphic_statement_in_a_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        if_statement" NEW_LINE
                       "            branch" NEW_LINE
                       "                declaration_statement" NEW_LINE
                       "                    variable" NEW_LINE
                       "                        type_reference: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "                binary" NEW_LINE
                       "                    operator: !=" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "                assignment_statement" NEW_LINE
                       "                    operator: =" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: U8" NEW_LINE
                       "        if_statement" NEW_LINE
                       "            branch" NEW_LINE
                       "                declaration_statement" NEW_LINE
                       "                    variable" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "                binary" NEW_LINE
                       "                    type: Bool" NEW_LINE
                       "                    operator: !=" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "                assignment_statement" NEW_LINE
                       "                    operator: =" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        call_expression" NEW_LINE
                       "            type: none" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Function()" NEW_LINE
                       "                name: a" NEW_LINE
                       "                actual_type_parameter: U8" NEW_LINE);
}

static void polymorphic_statement_in_a_polymorphic_function(void)
{
    format_test_name("semantics/statements/if/polymorphic_statement_in_a_polymorphic_function");

    format_source_path(0, "semantics/statements/if/polymorphic_statement_in_a_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]()\n"
                          "    if T b = 0; b != 0\n"
                          "        b = 0"
                          "    end\n"
                          "end\n"
                          "\n"
                          "function c()\n"
                          "    a[U8]()\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/polymorphic_statement_in_a_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/if/polymorphic_statement_in_a_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        if_statement" NEW_LINE
                       "            branch" NEW_LINE
                       "                declaration_statement" NEW_LINE
                       "                    variable" NEW_LINE
                       "                        type_reference: T" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "                binary" NEW_LINE
                       "                    operator: !=" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "                assignment_statement" NEW_LINE
                       "                    operator: =" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: U8" NEW_LINE
                       "        if_statement" NEW_LINE
                       "            branch" NEW_LINE
                       "                declaration_statement" NEW_LINE
                       "                    variable" NEW_LINE
                       "                        type: U8" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: U8" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "                binary" NEW_LINE
                       "                    type: Bool" NEW_LINE
                       "                    operator: !=" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: U8" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: U8" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "                assignment_statement" NEW_LINE
                       "                    operator: =" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: U8" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: U8" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        call_expression" NEW_LINE
                       "            type: none" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Function()" NEW_LINE
                       "                name: a" NEW_LINE
                       "                actual_type_parameter: U8" NEW_LINE);
}

static void redeclare_variable_declared_before_body(void)
{
    format_test_name("semantics/statements/if/redeclare_variable_declared_before_body");

    format_source_path(0, "semantics/statements/if/redeclare_variable_declared_before_body.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    if I32 b = 0; false\n"
                          "        I32 b = 42\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/redeclare_variable_declared_before_body.owen");

    format_expectation(&test.expected_error, 
                       "%s:6:13: b is already defined." NEW_LINE,
                       test.source_paths[0]);
}

static void redeclare_variable_declared_in_the_outer_scope(void)
{
    format_test_name("semantics/statements/if/redeclare_variable_declared_in_the_outer_scope");

    format_source_path(0, "semantics/statements/if/redeclare_variable_declared_in_the_outer_scope.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    I32 b = 0\n"
                          "    \n"
                          "    if false\n"
                          "        I32 b = 42\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/redeclare_variable_declared_in_the_outer_scope.owen");

    format_expectation(&test.expected_error, 
                       "%s:8:13: b is already defined." NEW_LINE,
                       test.source_paths[0]);
}

static void refer_to_variable_declared_before_body_in_the_inner_scope(void)
{
    format_test_name("semantics/statements/if/refer_to_variable_declared_before_body_in_the_inner_scope");

    format_source_path(0, "semantics/statements/if/refer_to_variable_declared_before_body_in_the_inner_scope.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    if I32 b = 0; false\n"
                          "        b = b\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/refer_to_variable_declared_before_body_in_the_inner_scope.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/if/refer_to_variable_declared_before_body_in_the_inner_scope.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        if_statement" NEW_LINE
                       "            branch" NEW_LINE
                       "                declaration_statement" NEW_LINE
                       "                    variable" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "                boolean_literal" NEW_LINE
                       "                    type: Bool" NEW_LINE
                       "                    value: false" NEW_LINE
                       "                assignment_statement" NEW_LINE
                       "                    operator: =" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE);
}

static void refer_to_variable_declared_in_body_in_the_inner_scope(void)
{
    format_test_name("semantics/statements/if/refer_to_variable_declared_in_body_in_the_inner_scope");

    format_source_path(0, "semantics/statements/if/refer_to_variable_declared_in_body_in_the_inner_scope.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    if false\n"
                          "        I32 b = 0\n"
                          "        b = b\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/refer_to_variable_declared_in_body_in_the_inner_scope.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/if/refer_to_variable_declared_in_body_in_the_inner_scope.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        if_statement" NEW_LINE
                       "            branch" NEW_LINE
                       "                boolean_literal" NEW_LINE
                       "                    type: Bool" NEW_LINE
                       "                    value: false" NEW_LINE
                       "                declaration_statement" NEW_LINE
                       "                    variable" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 0" NEW_LINE
                       "                assignment_statement" NEW_LINE
                       "                    operator: =" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE);
}

static void refer_to_variable_declared_in_the_outer_scope_inside_inner_scope(void)
{
    format_test_name("semantics/statements/if/refer_to_variable_declared_in_the_outer_scope_inside_inner_scope");

    format_source_path(0, "semantics/statements/if/refer_to_variable_declared_in_the_outer_scope_inside_inner_scope.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function do_stuff()\n"
                          "    I32 a = 0\n"
                          "    \n"
                          "    if false\n"
                          "        a = a\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/refer_to_variable_declared_in_the_outer_scope_inside_inner_scope.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/if/refer_to_variable_declared_in_the_outer_scope_inside_inner_scope.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: do_stuff" NEW_LINE
                       "        declaration_statement" NEW_LINE
                       "            variable" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: a" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE
                       "        if_statement" NEW_LINE
                       "            branch" NEW_LINE
                       "                boolean_literal" NEW_LINE
                       "                    type: Bool" NEW_LINE
                       "                    value: false" NEW_LINE
                       "                assignment_statement" NEW_LINE
                       "                    operator: =" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: a" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: a" NEW_LINE);
}

static void unused_variable_declared_before_body(void)
{
    format_test_name("semantics/statements/if/unused_variable_declared_before_body");

    format_source_path(0, "semantics/statements/if/unused_variable_declared_before_body.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    if I32 b = 0; false\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/unused_variable_declared_before_body.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:12: Unused variable." NEW_LINE,
                       test.source_paths[0]);
}

static void unused_variable_declared_in_body(void)
{
    format_test_name("semantics/statements/if/unused_variable_declared_in_body");

    format_source_path(0, "semantics/statements/if/unused_variable_declared_in_body.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    if false\n"
                          "        I32 b = 0\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/unused_variable_declared_in_body.owen");
    format_expectation(&test.expected_error, 
                       "%s:6:13: Unused variable." NEW_LINE,
                       test.source_paths[0]);
}

static void refer_to_variable_declared_in_earlier_branch(void)
{
    format_test_name("semantics/statements/if/refer_to_variable_declared_in_earlier_branch");

    format_source_path(0, "semantics/statements/if/refer_to_variable_declared_in_earlier_branch.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a() : I32\n"
                          "    if I32 b = 4; b == 1\n"
                          "        return 1\n"
                          "    elif b == 2\n"
                          "        return 2\n"
                          "    elif b == 3\n"
                          "        return 3\n"
                          "    else\n"
                          "        return b\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/refer_to_variable_declared_in_earlier_branch.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/statements/if/refer_to_variable_declared_in_earlier_branch.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        if_statement" NEW_LINE
                       "            branch" NEW_LINE
                       "                declaration_statement" NEW_LINE
                       "                    variable" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 4" NEW_LINE
                       "                binary" NEW_LINE
                       "                    type: Bool" NEW_LINE
                       "                    operator: ==" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 1" NEW_LINE
                       "                return_statement" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 1" NEW_LINE
                       "            branch" NEW_LINE
                       "                binary" NEW_LINE
                       "                    type: Bool" NEW_LINE
                       "                    operator: ==" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 2" NEW_LINE
                       "                return_statement" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 2" NEW_LINE
                       "            branch" NEW_LINE
                       "                binary" NEW_LINE
                       "                    type: Bool" NEW_LINE
                       "                    operator: ==" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 3" NEW_LINE
                       "                return_statement" NEW_LINE
                       "                    integer_literal" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        value: 3" NEW_LINE
                       "            branch" NEW_LINE
                       "                return_statement" NEW_LINE
                       "                    reference_expression" NEW_LINE
                       "                        type: I32" NEW_LINE
                       "                        name: b" NEW_LINE);
}

static void refer_to_variable_declared_in_branch_body(void)
{
    format_test_name("semantics/statements/if/refer_to_variable_declared_in_branch_body");

    format_source_path(0, "semantics/statements/if/refer_to_variable_declared_in_branch_body.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a() : I32\n"
                          "    if false\n"
                          "        I32 b = 4"
                          "        return b\n"
                          "    else\n"
                          "        return b\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/refer_to_variable_declared_in_branch_body.owen");

    format_expectation(&test.expected_error, 
                       "%s:8:16: b is undefined." NEW_LINE,
                       test.source_paths[0]);
}

static bool dereferenced_condition(void)
{
    static uint8_t type_index = 0;
    while (true)
    {
        if (type_index > LAST_TYPE_INDEX)
            return false;

        bool is_valid_case = type_index >= FIRST_POINTER_TYPE_INDEX && type_index <= LAST_POINTER_TYPE_INDEX;
        if (is_valid_case)
        {
            format_test_name("semantics/statements/if/dereferenced_%s_typed_condition", types[type_index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(%s b)\n"
                                  "    if @b == 1\n"
                                  "    end\n"
                                  "end",
                                  types[type_index].name);

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            if (is_readable_type(type_index))
            {
                format_expectation(&test.expected_semantics,
                                   "file" NEW_LINE
                                   "    path: %s" NEW_LINE
                                   "    namespace: Abc" NEW_LINE
                                   "    function" NEW_LINE
                                   "        name: a" NEW_LINE
                                   "        formal_parameter" NEW_LINE
                                   "            type: %s" NEW_LINE
                                   "            name: b" NEW_LINE
                                   "        if_statement" NEW_LINE
                                   "            branch" NEW_LINE
                                   "                binary" NEW_LINE
                                   "                    type: Bool" NEW_LINE
                                   "                    operator: ==" NEW_LINE
                                   "                    dereference" NEW_LINE
                                   "                        type: I32" NEW_LINE
                                   "                        reference_expression" NEW_LINE
                                   "                            type: %s" NEW_LINE
                                   "                            name: b" NEW_LINE
                                   "                    integer_literal" NEW_LINE
                                   "                        type: I32" NEW_LINE
                                   "                        value: 1" NEW_LINE,
                                   test.source_paths[0],
                                   types[type_index].name,
                                   types[type_index].name);
            }
            else
            {
                format_expectation(&test.expected_error, 
                                   "%s:5:8: Missing readable privilege (?) from %s." NEW_LINE,
                                   test.source_paths[0],
                                   types[type_index].name);
            }
        }

        type_index++;
        if (is_valid_case)
            return true;
    }
}

static bool pointer_typed_field_access(void)
{
    static uint8_t state;
    switch (state++)
    {
        case 0:
            format_test_name("semantics/statements/if/field_access_to_pointer_readable_condition");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "function a(#?A b)\n"
                                  "    if b.a == 1\n"
                                  "    end\n"
                                  "end");

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics,
                               "file" NEW_LINE
                               "    path: %s" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    structure" NEW_LINE
                               "        name: A" NEW_LINE
                               "        is_public: false" NEW_LINE
                               "        field" NEW_LINE
                               "            type: I32" NEW_LINE
                               "            name: a" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: #?A" NEW_LINE
                               "            name: b" NEW_LINE
                               "        if_statement" NEW_LINE
                               "            branch" NEW_LINE
                               "                binary" NEW_LINE
                               "                    type: Bool" NEW_LINE
                               "                    operator: ==" NEW_LINE
                               "                    field_access" NEW_LINE
                               "                        type: I32" NEW_LINE
                               "                        reference_expression" NEW_LINE
                               "                            type: #?A" NEW_LINE
                               "                            name: b" NEW_LINE
                               "                        field: a" NEW_LINE
                               "                    integer_literal" NEW_LINE
                               "                        type: I32" NEW_LINE
                               "                        value: 1" NEW_LINE,
                               test.source_paths[0]);

            return true;
        
        case 1:
            format_test_name("semantics/statements/if/field_access_to_pointer_condition");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "structure A\n"
                                  "    I32 a\n"
                                  "end\n"
                                  "\n"
                                  "function a(#A b)\n"
                                  "    if b.a == 1\n"
                                  "    end\n"
                                  "end");

            format_command_line_options(test.source_paths[0]);
            format_expectation(&test.expected_error,
                               "%s:9:8: Missing readable privilege (?) from #A." NEW_LINE,
                               test.source_paths[0]);

            return true;

        default:
            return false;
    }
}

static bool pointer_typed_array_access(void)
{
    static uint8_t state;
    switch (state++)
    {
        case 0:
            format_test_name("semantics/statements/if/array_access_to_pointer_readable_condition");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(#?[]I32 b)\n"
                                  "    if b[0] == 1\n"
                                  "    end\n"
                                  "end");

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics,
                               "file" NEW_LINE
                               "    path: semantics/statements/if/array_access_to_pointer_readable_condition.owen" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: #?[]I32" NEW_LINE
                               "            name: b" NEW_LINE
                               "        if_statement" NEW_LINE
                               "            branch" NEW_LINE
                               "                binary" NEW_LINE
                               "                    type: Bool" NEW_LINE
                               "                    operator: ==" NEW_LINE
                               "                    array_access" NEW_LINE
                               "                        type: I32" NEW_LINE
                               "                        reference_expression" NEW_LINE
                               "                            type: #?[]I32" NEW_LINE
                               "                            name: b" NEW_LINE
                               "                        integer_literal" NEW_LINE
                               "                            type: U32" NEW_LINE
                               "                            value: 0" NEW_LINE
                               "                    integer_literal" NEW_LINE
                               "                        type: I32" NEW_LINE
                               "                        value: 1" NEW_LINE,
                               test.source_paths[0]);

            return true;
        
        case 1:
            format_test_name("semantics/statements/if/array_access_to_pointer_condition");

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a(#[]I32 b)\n"
                                  "    if b[0] == 1\n"
                                  "    end\n"
                                  "end");

            format_command_line_options(test.source_paths[0]);
            format_expectation(&test.expected_error,
                               "%s:5:8: Missing readable privilege (?) from #[]I32." NEW_LINE,
                               test.source_paths[0]);

            return true;

        default:
            return false;
    }
}

static void all_branches_terminate_but_has_no_else_branch(void)
{
    format_test_name("semantics/statements/if/all_branches_terminate_but_has_no_else_branch");

    format_source_path(0, "semantics/statements/if/all_branches_terminate_but_has_no_else_branch.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a() : I32\n"
                          "    if false\n"
                          "        return 1\n"
                          "    elif false\n"
                          "        return 2\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/all_branches_terminate_but_has_no_else_branch.owen");

    format_expectation(&test.expected_error, 
                       "%s:4:10: Missing terminating statement." NEW_LINE,
                       test.source_paths[0]);
}

static void not_all_branches_terminate_but_has_else_branch(void)
{
    format_test_name("semantics/statements/if/not_all_branches_terminate_but_has_else_branch");

    format_source_path(0, "semantics/statements/if/not_all_branches_terminate_but_has_else_branch.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a() : I32\n"
                          "    if false\n"
                          "    else\n"
                          "        return 2\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/not_all_branches_terminate_but_has_else_branch.owen");

    format_expectation(&test.expected_error, 
                       "%s:4:10: Missing terminating statement." NEW_LINE,
                       test.source_paths[0]);
}

static void non_terminating_if_branch(void)
{
    format_test_name("semantics/statements/if/non_terminating_if_branch");

    format_source_path(0, "semantics/statements/if/non_terminating_if_branch.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a() : I32\n"
                          "    if false\n"
                          "    end\n"
                          "end");

    SET_COMMAND_LINE("semantics/statements/if/non_terminating_if_branch.owen");

    format_expectation(&test.expected_error, 
                       "%s:4:10: Missing terminating statement." NEW_LINE,
                       test.source_paths[0]);
}

bool semantics_statements_if(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            if (x_typed_condition())
                break;

            state++;

        case 1:
            monomorphic_statement_in_a_polymorphic_function();
            state++;
            break;

        case 2:
            polymorphic_statement_in_a_polymorphic_function();
            state++;
            break;

        case 3:
            redeclare_variable_declared_before_body();
            state++;
            break;

        case 4:
            redeclare_variable_declared_in_the_outer_scope();
            state++;
            break;

        case 5:
            refer_to_variable_declared_before_body_in_the_inner_scope();
            state++;
            break;

        case 6:
            refer_to_variable_declared_in_body_in_the_inner_scope();
            state++;
            break;

        case 7:
            refer_to_variable_declared_in_the_outer_scope_inside_inner_scope();
            state++;
            break;

        case 8:
            unused_variable_declared_before_body();
            state++;
            break;

        case 9:
            unused_variable_declared_in_body();
            state++;
            break;

        case 10:
            refer_to_variable_declared_in_earlier_branch();
            state++;
            break;

        case 11:
            refer_to_variable_declared_in_branch_body();
            state++;
            break;

        case 12:
            if (dereferenced_condition())
                break;

            state++;

        case 13:
            if (pointer_typed_field_access())
                break;

            state++;
            
        case 14:
            if (pointer_typed_array_access())
                break;

            state++;

        case 15:
            all_branches_terminate_but_has_no_else_branch();
            state++;
            break;

        case 16:
            not_all_branches_terminate_but_has_else_branch();
            state++;
            break;

        case 17:
            non_terminating_if_branch();
            state++;
            break;

        default:
            return false;
    }

    return true;
}
