#include "runner.h"

static void monomorphic_reference_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/reference/monomorphic_reference_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/reference/monomorphic_reference_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](I32 b) : I32\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(I32 d) : I32\n"
                          "    return a[I32](d)\n"
                          "end\n");

    SET_COMMAND_LINE("semantics/expressions/reference/monomorphic_reference_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/reference/monomorphic_reference_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: d" NEW_LINE);
}

static void polymorphic_reference_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/reference/polymorphic_reference_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/reference/polymorphic_reference_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](T b) : T\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(I32 d) : I32\n"
                          "    return a(d)\n"
                          "end\n");

    SET_COMMAND_LINE("semantics/expressions/reference/polymorphic_reference_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/reference/polymorphic_reference_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: d" NEW_LINE);
}

static void reference_a_parameter(void)
{
    format_test_name("semantics/expressions/reference/reference_a_parameter");

    format_source_path(0, "semantics/expressions/reference/reference_a_parameter.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(Function() b) : Function()\n"
                          "    return b\n"
                          "end\n");

    SET_COMMAND_LINE("semantics/expressions/reference/reference_a_parameter.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/reference/reference_a_parameter.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: Function()" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: Function()" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Function()" NEW_LINE
                       "                name: b" NEW_LINE);
}

static void reference_a_variable(void)
{
    format_test_name("semantics/expressions/reference/reference_a_variable");

    format_source_path(0, "semantics/expressions/reference/reference_a_variable.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a() : I32\n"
                          "    I32 b = 0\n"
                          "\n"
                          "    return b\n"
                          "end\n");

    SET_COMMAND_LINE("semantics/expressions/reference/reference_a_variable.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/reference/reference_a_variable.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        declaration_statement" NEW_LINE
                       "            variable" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE);
}

static void undefined_reference(void)
{
    format_test_name("semantics/expressions/reference/undefined_reference");

    format_source_path(0, "semantics/expressions/reference/undefined_reference.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a() : I32\n"
                          "    return b\n"
                          "end\n");

    SET_COMMAND_LINE("semantics/expressions/reference/undefined_reference.owen");
    format_expectation(&test.expected_error, 
                       "%s:5:12: b is undefined." NEW_LINE,
                       test.source_paths[0]);
}

bool semantics_expressions_reference(void)
{
    static uint8_t state;
    switch (state++)
    {
        case 0:
            monomorphic_reference_in_polymorphic_function();
            break;

        case 1:
            polymorphic_reference_in_polymorphic_function();
            break;

        case 2:
            reference_a_parameter();
            break;

        case 3:
            reference_a_variable();
            break;

        case 4:
            undefined_reference();
            break;

        default:
            return false;
    }

    return true;
}
