#include "runner.h"

static bool x_typed_literal(void)
{
    static uint8_t type_index = 0;
    if (type_index > LAST_TYPE_INDEX)
        return false;

    format_test_name("semantics/expressions/unicode_code_point_literal/%s_typed_literal", types[type_index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration Enumeration : I32\n"
                          "    a\n"
                          "end\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "structure Structure[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "union Union\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "union Union[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function a() : %s\n"
                          "    return 'a'\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end",
                          types[type_index].name);

    format_command_line_options("%s -print-semantics", test.source_paths[0]);
    if (type_index >= FIRST_INTEGER_TYPE_INDEX && type_index <= LAST_INTEGER_TYPE_INDEX)
    {
        format_expectation(&test.expected_semantics, 
                           "file" NEW_LINE
                           "    path: %s" NEW_LINE
                           "    namespace: Abc" NEW_LINE
                           "    enumeration" NEW_LINE
                           "        name: Enumeration" NEW_LINE
                           "        underlying_type: I32" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        constant" NEW_LINE
                           "            name: a" NEW_LINE
                           "            value: 0" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    structure" NEW_LINE
                           "        name: Structure" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        field" NEW_LINE
                           "            type: I32" NEW_LINE
                           "            name: a" NEW_LINE
                           "    union" NEW_LINE
                           "        name: Union" NEW_LINE
                           "        is_public: false" NEW_LINE
                           "        formal_type_parameter: T" NEW_LINE
                           "        field" NEW_LINE
                           "            type_reference: T" NEW_LINE
                           "            name: a" NEW_LINE
                           "    function" NEW_LINE
                           "        name: a" NEW_LINE
                           "        return_type: %s" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            integer_literal" NEW_LINE
                           "                type: %s" NEW_LINE
                           "                value: 97" NEW_LINE
                           "    function" NEW_LINE
                           "        name: main" NEW_LINE
                           "        return_type: I32" NEW_LINE
                           "        return_statement" NEW_LINE
                           "            integer_literal" NEW_LINE
                           "                type: I32" NEW_LINE
                           "                value: 0" NEW_LINE,
                           test.source_paths[0],
                           types[type_index].name,
                           types[type_index].name);
    }
    else
    {
        format_expectation(&test.expected_error, 
                           "%s:25:12: Cannot infer literal as %s." NEW_LINE,
                           test.source_paths[0],
                           types[type_index].name);
    }

    type_index++;

    return true;
}

bool semantics_expressions_unicode_code_point_literal(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            if (x_typed_literal())
                break;

            state++;

        default:
            return false;
    }

    return true;
}
