#include "runner.h"

static void actual_type_parameter_not_matching_formal_type_parameter(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/actual_type_parameter_not_matching_formal_type_parameter");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](T b) : T\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(I32 d) : I32\n"
                          "    return a[U8](d)\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/actual_type_parameter_not_matching_formal_type_parameter.owen");
    format_expectation(&test.expected_error, 
                       "%s:9:12: No matching signature for a." NEW_LINE
                       "Declarations:" NEW_LINE
                       "    %s:4:10: a[T](T b) : T" NEW_LINE,
                       test.source_paths[0],
                       test.source_paths[0]);
}

static void actual_type_parameters_make_signature_match_monomorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/actual_type_parameters_make_signature_match_monomorphic_function");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b) : I32\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function a[T](T b) : T\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(I32 d) : I32\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/actual_type_parameters_make_signature_match_monomorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/actual_type_parameters_make_signature_match_monomorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void call_reference_that_is_not_a_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/call_reference_that_is_not_a_function");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a(I32 b)\n"
                          "    b[Bool]()\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/call_reference_that_is_not_a_function.owen");

    format_expectation(&test.expected_error, 
                       "%s:5:5: b is not a function." NEW_LINE,
                       test.source_paths[0]);
}

static void call_undefined_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/call_undefined_function");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a()\n"
                          "    b[I32]()\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/call_undefined_function.owen");

    format_expectation(&test.expected_error, 
                       "%s:5:5: b is undefined." NEW_LINE,
                       test.source_paths[0]);
}

static void error_nested_in_a_polymorphic_function_call(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/error_nested_in_a_polymorphic_function_call");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration Direction : U8\n"
                          "    up\n"
                          "    right\n"
                          "    down\n"
                          "    left\n"
                          "end\n"
                          "\n"
                          "function do_stuff() : Direction\n"
                          "    return do_stuff[Direction](Direction.up, Direction.down)\n"
                          "end\n"
                          "\n"
                          "function do_stuff[T](T a, T b) : T\n"
                          "    return a + b\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/error_nested_in_a_polymorphic_function_call.owen");

    format_expectation(&test.expected_error, 
                       "semantics/expressions/call/explicit_actual_type_parameters/error_nested_in_a_polymorphic_function_call.owen:16:14: Operator not defined for Direction and Direction." NEW_LINE
                       "Polymorphic stack:" NEW_LINE
                       "    semantics/expressions/call/explicit_actual_type_parameters/error_nested_in_a_polymorphic_function_call.owen:12:12: do_stuff[Direction](Direction a, Direction b) : Direction" NEW_LINE);
}

static void error_nested_in_multiple_polymorphic_function_calls(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/error_nested_in_multiple_polymorphic_function_calls");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "enumeration Direction : U8\n"
                          "    up\n"
                          "    right\n"
                          "    down\n"
                          "    left\n"
                          "end\n"
                          "\n"
                          "function do_stuff() : Direction\n"
                          "    return do_stuff[Direction](Direction.up)\n"
                          "end\n"
                          "\n"
                          "function do_stuff[T](T a) : T\n"
                          "    return do_stuff(a, a)\n"
                          "end\n"
                          "\n"
                          "function do_stuff[T](T a, T b) : T\n"
                          "    return a + b\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/error_nested_in_multiple_polymorphic_function_calls.owen");

    format_expectation(&test.expected_error, 
                       "semantics/expressions/call/explicit_actual_type_parameters/error_nested_in_multiple_polymorphic_function_calls.owen:20:14: Operator not defined for Direction and Direction." NEW_LINE
                       "Polymorphic stack:" NEW_LINE
                       "    semantics/expressions/call/explicit_actual_type_parameters/error_nested_in_multiple_polymorphic_function_calls.owen:12:12: do_stuff[Direction](Direction a) : Direction" NEW_LINE
                       "    semantics/expressions/call/explicit_actual_type_parameters/error_nested_in_multiple_polymorphic_function_calls.owen:16:20: do_stuff[Direction](Direction a, Direction b) : Direction" NEW_LINE);
}

static bool literal_as_actual_parameter(void)
{
    static uint8_t index = 0;
    while (index < TYPES_LENGTH && !types[index].default_value_name)
        index++;

    if (index == TYPES_LENGTH)
        return false;

    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/%s_literal_where_%s_typed_actual_parameter_expected", types[index].file_friendly_default_value_name, types[index].file_friendly_name);

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure Structure\n"
                          "    I32 a\n"
                          "end\n"
                          "\n"
                          "function a[T](T b) : T\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c()\n"
                          "    a[%s](%s)\n"
                          "end", 
                          types[index].name, types[index].default_value);

    format_command_line_options("%s", test.source_paths[0]);
    format_expectation(&test.expected_error, 
                       "%s:13:%u: %s type cannot be inferred." NEW_LINE,
                       test.source_paths[0],
                       9 + strlen(types[index].name),
                       types[index].default_value_name);

    index++;
    return true;
}

static void missing_multiple_actual_type_parameters(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/missing_multiple_actual_type_parameters");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T1, T2]() : T1\n"
                          "    return 0\n"
                          "end\n"
                          "\n"
                          "function c() : I32\n"
                          "    return a()\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/missing_multiple_actual_type_parameters.owen");

    format_expectation(&test.expected_error, 
                       "%s:9:13: T1 could not be inferred from the call site. Specify it explicitly." NEW_LINE,
                       test.source_paths[0]);
}

static void missing_one_actual_type_parameter(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/missing_one_actual_type_parameter");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]() : T\n"
                          "    return 0\n"
                          "end\n"
                          "\n"
                          "function b() : I32\n"
                          "    return a()\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/missing_one_actual_type_parameter.owen");

    format_expectation(&test.expected_error, 
                       "%s:9:13: T could not be inferred from the call site. Specify it explicitly." NEW_LINE,
                       test.source_paths[0]);
}

static void specifying_all_formal_type_parameters(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/specifying_all_formal_type_parameters");

    format_source_path(0, "%s.owen", test.name);
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]() : T\n"
                          "    return 0\n"
                          "end\n"
                          "\n"
                          "function b() : I32\n"
                          "    return a[I32]()\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/specifying_all_formal_type_parameters.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/specifying_all_formal_type_parameters.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function() : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static bool pass_x_typed_expression_to_compatible_formal_parameter(void)
{
    static uint8_t lhs_index = FIRST_POINTER_TYPE_INDEX;
    static uint8_t rhs_index = FIRST_POINTER_TYPE_INDEX;

    while (true)
    {
        if (lhs_index > LAST_POINTER_TYPE_INDEX)
            return false;

        bool is_valid_case = pointer_type_is_compatible_with(lhs_index, rhs_index) &&
                             pointer_is_retained(lhs_index) && 
                             pointer_is_retained(rhs_index);

        if (is_valid_case)
        {
            format_test_name("semantics/expressions/call/explicit_actual_type_parameters/pass_%s_typed_expression_to_%s_typed_formal_parameter", types[lhs_index].file_friendly_name, types[rhs_index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a[T](T b) : T\n"
                                  "    return b\n"
                                  "end\n"
                                  "\n"
                                  "function c(%s d) : %s\n"
                                  "    return a[%s](d)\n"
                                  "end\n"
                                  "\n"
                                  "function main() : I32\n"
                                  "    return 0\n"
                                  "end", 
                                  types[lhs_index].name, types[rhs_index].name, 
                                  types[lhs_index].name);

            format_command_line_options("%s -print-semantics", test.source_paths[0]);
            format_expectation(&test.expected_semantics, 
                               "file" NEW_LINE
                               "    path: %s" NEW_LINE
                               "    namespace: Abc" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        formal_type_parameter: T" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type_reference: T" NEW_LINE
                               "            name: b" NEW_LINE
                               "        return_type_reference: T" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            reference_expression" NEW_LINE
                               "                name: b" NEW_LINE
                               "    function" NEW_LINE
                               "        name: a" NEW_LINE
                               "        actual_type_parameter: %s" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: %s" NEW_LINE
                               "            name: b" NEW_LINE
                               "        return_type: %s" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            reference_expression" NEW_LINE
                               "                type: %s" NEW_LINE
                               "                name: b" NEW_LINE
                               "    function" NEW_LINE
                               "        name: c" NEW_LINE
                               "        formal_parameter" NEW_LINE
                               "            type: %s" NEW_LINE
                               "            name: d" NEW_LINE
                               "        return_type: %s" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            call_expression" NEW_LINE
                               "                type: %s" NEW_LINE
                               "                reference_expression" NEW_LINE
                               "                    type: Function(%s) : %s" NEW_LINE
                               "                    name: a" NEW_LINE
                               "                    actual_type_parameter: %s" NEW_LINE
                               "                reference_expression" NEW_LINE
                               "                    type: %s" NEW_LINE
                               "                    name: d" NEW_LINE
                               "    function" NEW_LINE
                               "        name: main" NEW_LINE
                               "        return_type: I32" NEW_LINE
                               "        return_statement" NEW_LINE
                               "            integer_literal" NEW_LINE
                               "                type: I32" NEW_LINE
                               "                value: 0" NEW_LINE,
                               test.source_paths[0],
                               types[lhs_index].name,
                               types[lhs_index].name, 
                               types[lhs_index].name, 
                               types[lhs_index].name, 
                               types[lhs_index].name, 
                               types[rhs_index].name, 
                               types[lhs_index].name, 
                               types[lhs_index].name, types[lhs_index].name, 
                               types[lhs_index].name, 
                               types[lhs_index].name);
        }

        if (rhs_index > LAST_POINTER_TYPE_INDEX)
        {
            rhs_index = FIRST_POINTER_TYPE_INDEX;
            lhs_index++;
        }
        else
            rhs_index++;

        if (is_valid_case)
            return true;
    }

    return false;
}

static bool pass_x_typed_expression_to_incompatible_formal_parameter(void)
{
    static uint8_t lhs_index = FIRST_POINTER_TYPE_INDEX;
    static uint8_t rhs_index = FIRST_POINTER_TYPE_INDEX;

    while (true)
    {
        if (lhs_index > LAST_POINTER_TYPE_INDEX)
            return false;

        bool is_valid_case = !pointer_type_is_compatible_with(lhs_index, rhs_index) &&
                              pointer_is_retained(lhs_index) && 
                              pointer_is_retained(rhs_index);

        if (is_valid_case)
        {
            format_test_name("semantics/expressions/call/explicit_actual_type_parameters/pass_%s_typed_expression_to_%s_typed_formal_parameter", types[lhs_index].file_friendly_name, types[rhs_index].file_friendly_name);

            format_source_path(0, "%s.owen", test.name);
            format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                                  "namespace Abc\n"
                                  "\n"
                                  "function a[T](T b) : T\n"
                                  "    return b\n"
                                  "end\n"
                                  "\n"
                                  "function c(%s d) : %s\n"
                                  "    return a[%s](d)\n"
                                  "end", 
                                  types[lhs_index].name, types[rhs_index].name, 
                                  types[rhs_index].name);

            format_command_line_options(test.source_paths[0]);
            format_expectation(&test.expected_error, 
                               "%s:9:12: No matching signature for a." NEW_LINE
                               "Declarations:" NEW_LINE
                               "    %s:4:10: a[T](T b) : T" NEW_LINE,
                               test.source_paths[0],
                               test.source_paths[0]);
        }

        if (rhs_index > LAST_POINTER_TYPE_INDEX)
        {
            rhs_index = FIRST_POINTER_TYPE_INDEX;
            lhs_index++;
        }
        else
            rhs_index++;

        if (is_valid_case)
            return true;
    }

    return false;
}

static void monomorphic_name_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_name_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/monomorphic_name_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](I32 b) : I32\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(I32 d) : I32\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_name_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/monomorphic_name_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void polymorphic_name_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_name_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/polymorphic_name_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](T b) : T\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(I32 d) : I32\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_name_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/polymorphic_name_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void monomorphic_pointer_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_pointer_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/monomorphic_pointer_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](#`I32 b) : #`I32\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(#`I32 d) : #`I32\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_pointer_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/monomorphic_pointer_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: #`I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: #`I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: #`I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: #`I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: #`I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: #`I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: #`I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: #`I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(#`I32) : #`I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: #`I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void polymorphic_pointer_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_pointer_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/polymorphic_pointer_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](#`T b) : #`T\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(#`I32 d) : #`I32\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_pointer_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/polymorphic_pointer_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: #`T" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: #`T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: #`I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: #`I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: #`I32" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: #`I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: #`I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: #`I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(#`I32) : #`I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: #`I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void polymorphic_non_matching_privilages_in_pointer_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_non_matching_privilages_in_pointer_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/polymorphic_non_matching_privilages_in_pointer_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](#`$T b) : #`T\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(#`I32 d) : #`I32\n"
                          "    return a[I32](d)\n"
                          "end\n");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_non_matching_privilages_in_pointer_typed_formal_parameter_in_polymorphic_function.owen");
    format_expectation(&test.expected_error, 
                       "%s:9:12: No matching signature for a." NEW_LINE
                       "Declarations:" NEW_LINE
                       "    %s:4:10: a[T](#`$T b) : #`T" NEW_LINE,
                       test.source_paths[0],
                       test.source_paths[0]);
}

static void monomorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/monomorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]([]I32 b) : I32\n"
                          "    return b[0]\n"
                          "end\n"
                          "\n"
                          "function c([]I32 d) : I32\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/monomorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: []I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            array_access" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: []I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            array_access" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: []I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: U32" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: []I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function([]I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: []I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void polymorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/polymorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]([]T b) : T\n"
                          "    return b[0]\n"
                          "end\n"
                          "\n"
                          "function c([]I32 d) : I32\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/polymorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: []T" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            array_access" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: []I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            array_access" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: []I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: U32" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: []I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function([]I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: []I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void monomorphic_fixed_array_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_fixed_array_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/monomorphic_fixed_array_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]([4]I32 b) : I32\n"
                          "    return b[0]\n"
                          "end\n"
                          "\n"
                          "function c([4]I32 d) : I32\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_fixed_array_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/monomorphic_fixed_array_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: [4]I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            array_access" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: [4]I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            array_access" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: [4]I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: U32" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: [4]I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function([4]I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: [4]I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void polymorphic_fixed_array_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_fixed_array_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/polymorphic_fixed_array_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]([4]T b) : T\n"
                          "    return b[0]\n"
                          "end\n"
                          "\n"
                          "function c([4]I32 d) : I32\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_fixed_array_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/polymorphic_fixed_array_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: [4]T" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            array_access" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: [4]I32" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            array_access" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: [4]I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                integer_literal" NEW_LINE
                       "                    type: U32" NEW_LINE
                       "                    value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: [4]I32" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function([4]I32) : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: [4]I32" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void monomorphic_function_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_function_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/monomorphic_function_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](Function(I32) b) : Function(I32)\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(Function(I32) d) : Function(I32)\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_function_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/monomorphic_function_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: Function(I32)" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: Function(I32)" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: Function(I32)" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: Function(I32)" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Function(I32)" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: Function(I32)" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: Function(I32)" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: Function(I32)" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(Function(I32)) : Function(I32)" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32)" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void polymorphic_function_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_function_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/polymorphic_function_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](Function(T) b) : Function(T)\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(Function(I32) d) : Function(I32)\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_function_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/polymorphic_function_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: Function(T)" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: Function(T)" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: Function(I32)" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: Function(I32)" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: Function(I32)" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: Function(I32)" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: Function(I32)" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: Function(I32)" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(Function(I32)) : Function(I32)" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(I32)" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void monomorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/monomorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure A[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function a[T](A[I32] b) : A[I32]\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(A[I32] d) : A[I32]\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/monomorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/monomorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        field" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: a" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: a" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: A[I32]" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: A[I32]" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: A[I32]" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: A[I32]" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: A[I32]" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: A[I32]" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: A[I32]" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: A[I32]" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(A[I32]) : A[I32]" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: A[I32]" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE );
}

static void polymorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/polymorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "structure A[T]\n"
                          "    T a\n"
                          "end\n"
                          "\n"
                          "function a[T](A[T] b) : A[T]\n"
                          "    return b\n"
                          "end\n"
                          "\n"
                          "function c(A[I32] d) : A[I32]\n"
                          "    return a[I32](d)\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/polymorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        field" NEW_LINE
                       "            type_reference: T" NEW_LINE
                       "            name: a" NEW_LINE
                       "    structure" NEW_LINE
                       "        name: A" NEW_LINE
                       "        is_public: false" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        field" NEW_LINE
                       "            type: I32" NEW_LINE
                       "            name: a" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type_reference: A[T]" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type_reference: A[T]" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: A[I32]" NEW_LINE
                       "            name: b" NEW_LINE
                       "        return_type: A[I32]" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            reference_expression" NEW_LINE
                       "                type: A[I32]" NEW_LINE
                       "                name: b" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        formal_parameter" NEW_LINE
                       "            type: A[I32]" NEW_LINE
                       "            name: d" NEW_LINE
                       "        return_type: A[I32]" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: A[I32]" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function(A[I32]) : A[I32]" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: A[I32]" NEW_LINE
                       "                    name: d" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void polymorphic_formal_type_parameter_used_as_explicit_type_parameter(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_formal_type_parameter_used_as_explicit_type_parameter");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/polymorphic_formal_type_parameter_used_as_explicit_type_parameter.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T]() : T\n"
                          "    return 0\n"
                          "end\n"
                          "\n"
                          "function b[T]() : T\n"
                          "    return a[T]()\n"
                          "end\n"
                          "\n"
                          "function c() : I32\n"
                          "    return b[I32]()\n"
                          "end\n"
                          "\n"
                          "function main() : I32\n"
                          "    return 0\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/polymorphic_formal_type_parameter_used_as_explicit_type_parameter.owen "
                     "-print-semantics");

    format_expectation(&test.expected_semantics, 
                       "file" NEW_LINE
                       "    path: semantics/expressions/call/explicit_actual_type_parameters/polymorphic_formal_type_parameter_used_as_explicit_type_parameter.owen" NEW_LINE
                       "    namespace: Abc" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: a" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE
                       "    function" NEW_LINE
                       "        name: b" NEW_LINE
                       "        formal_type_parameter: T" NEW_LINE
                       "        return_type_reference: T" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: T" NEW_LINE
                       "    function" NEW_LINE
                       "        name: b" NEW_LINE
                       "        actual_type_parameter: I32" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function() : I32" NEW_LINE
                       "                    name: a" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "    function" NEW_LINE
                       "        name: c" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            call_expression" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                reference_expression" NEW_LINE
                       "                    type: Function() : I32" NEW_LINE
                       "                    name: b" NEW_LINE
                       "                    actual_type_parameter: I32" NEW_LINE
                       "    function" NEW_LINE
                       "        name: main" NEW_LINE
                       "        return_type: I32" NEW_LINE
                       "        return_statement" NEW_LINE
                       "            integer_literal" NEW_LINE
                       "                type: I32" NEW_LINE
                       "                value: 0" NEW_LINE);
}

static void retain_address_of_unretainable_expression(void)
{
    format_test_name("semantics/expressions/call/explicit_actual_type_parameters/retain_address_of_unretainable_expression");

    format_source_path(0, "semantics/expressions/call/explicit_actual_type_parameters/retain_address_of_unretainable_expression.owen");
    format_source_file(0, "// Generated by " __FILE__ " " __FUNCSIG__ "\n"
                          "namespace Abc\n"
                          "\n"
                          "function a[T](#`T b)\n"
                          "    T c = 0\n"
                          "    b = #c\n"
                          "end\n"
                          "\n"
                          "function d(#`I32 e)\n"
                          "    a[I32](e)\n"
                          "end");

    SET_COMMAND_LINE("semantics/expressions/call/explicit_actual_type_parameters/retain_address_of_unretainable_expression.owen");
    format_expectation(&test.expected_error, 
                       "%s:6:10: Parameters and variables cannot be retained." NEW_LINE
                       "Polymorphic stack:" NEW_LINE
                       "    %s:10:5: a[I32](#`I32 b)" NEW_LINE,
                       test.source_paths[0],
                       test.source_paths[0]);
}

bool semantics_expressions_call_explicit_actual_type_parameters(void)
{
    static uint8_t state;
    switch (state)
    {
        case 0:
            actual_type_parameter_not_matching_formal_type_parameter();
            state++;
            break;

        case 1:
            actual_type_parameters_make_signature_match_monomorphic_function();
            state++;
            break;

        case 2:
            call_reference_that_is_not_a_function();
            state++;
            break;

        case 3:
            call_undefined_function();
            state++;
            break;

        case 4:
            error_nested_in_a_polymorphic_function_call();
            state++;
            break;

        case 5:
            error_nested_in_multiple_polymorphic_function_calls();
            state++;
            break;

        case 6:
            if (literal_as_actual_parameter())
                break;
            
            state++;

        case 7:
            missing_multiple_actual_type_parameters();
            state++;
            break;

        case 8:
            missing_one_actual_type_parameter();
            state++;
            break;

        case 9:
            specifying_all_formal_type_parameters();
            state++;
            break;

        case 10:
            if (pass_x_typed_expression_to_compatible_formal_parameter())
                break;

            state++;

        case 11:
            if (pass_x_typed_expression_to_incompatible_formal_parameter())
                break;

            state++;

        case 12:
            monomorphic_name_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 13:
            polymorphic_name_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 14:
            monomorphic_pointer_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 15:
            polymorphic_pointer_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 16:
            polymorphic_non_matching_privilages_in_pointer_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 17:
            monomorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 18:
            polymorphic_dynamic_array_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 19:
            monomorphic_fixed_array_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 20:
            polymorphic_fixed_array_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 21:
            monomorphic_function_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 22:
            polymorphic_function_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 23:
            monomorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 24:
            polymorphic_actual_type_parameter_for_polymorphic_compound_typed_formal_parameter_in_polymorphic_function();
            state++;
            break;

        case 25:
            polymorphic_formal_type_parameter_used_as_explicit_type_parameter();
            state++;
            break;

        case 26:
            retain_address_of_unretainable_expression();
            state++;
            break;

        default:
            return false;
    }

    return true;
}
