#include "runner.h"

Type types[TYPES_LENGTH] =
{
    { "Bool",                  "bool",                     "false",     NULL,       NULL,       "#Bool",                  "bool_pointer",                     NULL,                   NULL,                   NULL,                   NULL,                   1,  1, Binary_Operator_Tag_logical_or | Binary_Operator_Tag_logical_and | Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal},
    { "I8",                    "i8",                       "0",         "integer",  "Integer",  "#I8",                    "i8_pointer",                       "-128",                 "127",                  "-129",                 "128",                  1,  1,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    { "I16",                   "i16",                      "0",         "integer",  "Integer",  "#I16",                   "i16_pointer",                      "-32768",               "32767",                "-32769",               "32768",                2,  2,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    { "I32",                   "i32",                      "0",         "integer",  "Integer",  "#I32",                   "i32_pointer",                      "-2147483648",          "2147483647",           "-2147483649",          "2147483648",           4,  4,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    { "I64",                   "i64",                      "0",         "integer",  "Integer",  "#I64",                   "i64_pointer",                      "-9223372036854775808", "9223372036854775807",  "-9223372036854775809", "9223372036854775808",  8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    { "U8",                    "u8",                       "0",         "integer",  "Integer",  "#U8",                    "u8_pointer",                       "0",                    "255",                  NULL,                   "256",                  1,  1,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    { "U16",                   "u16",                      "0",         "integer",  "Integer",  "#U16",                   "u16_pointer",                      "0",                    "65535",                NULL,                   "65_536",               2,  2,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    { "U32",                   "u32",                      "0",         "integer",  "Integer",  "#U32",                   "u32_pointer",                      "0",                    "4294967295",           NULL,                   "4294967296",           4,  4,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    { "U64",                   "u64",                      "0",         "integer",  "Integer",  "#U64",                   "u64_pointer",                      "0",                    "18446744073709551615", NULL,                   "18446744073709551616", 8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    { "F32",                   "f32",                      "0.0",       "float",    "Float",    "#F32",                   "f32_pointer",                      NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus                                                                    | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo                                                                                                      },
    { "F64",                   "f64",                      "0.0",       "float",    "Float",    "#F64",                   "f64_pointer",                      NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus                                                                    | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo                                                                                                      },
    { "Enumeration",           "enumeration",              NULL,        NULL,       NULL,       "#Enumeration",           "enumeration_pointer",              NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                        | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor                                                                                          | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    { "Union",                 "monomorphic_union",        "{ a = 0 }", "compound", "Compound", "#Union",                 "monomorphic_union_pointer",        NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
    { "Union[I32]",            "polymorphic_union",        "{ a = 0 }", "compound", "Compound", "#Union[I32]",            "polymorphic_union_pointer",        NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
    { "Structure",             "monomorphic_structure",    "{ a = 0 }", "compound", "Compound", "#Structure",             "monomorphic_structure_pointer",    NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
    { "Structure[I32]",        "polymorphic_structure",    "{ a = 0 }", "compound", "Compound", "#Structure[I32]",        "polymorphic_structure_pointer",    NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
    { "#I32",                  "pointer",                  NULL,        NULL,       NULL,       "##I32",                  "pointer_pointer",                  NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    { "readonly #I32",         "readonly_pointer",         NULL,        NULL,       NULL,       "readonly ##I32",         "readonly_pointer_pointer",         NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    { "readonly noalias #I32", "readonly_noalias_pointer", NULL,        NULL,       NULL,       "readonly noalias ##I32", "readonly_noalias_pointer_pointer", NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    { "noalias #I32",          "noalias_pointer",          NULL,        NULL,       NULL,       "noalias ##I32",          "noalias_pointer_pointer",          NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    { "[]I32",                 "dynamic_array",            NULL,        NULL,       NULL,       "#[]I32",                 "dynamic_array_pointer",            NULL,                   NULL,                   NULL,                   NULL,                   16, 16,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   },
    { "[4]I32",                "fixed_array",              "{ 0 }",     "array",    "Array",    "#[4]I32",                "fixed_array_pointer",              NULL,                   NULL,                   NULL,                   NULL,                   16, 16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
    { "Function()",            "function",                 NULL,        NULL,       NULL,       "#Function()",            "function_pointer",                 NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
};

bool is_readonly_type(const char* type)
{
    return strstr(type, "readonly");
}

bool is_noalias_type(const char* type)
{
    return strstr(type, "noalias");
}

bool is_qualified_type(const char* type)
{
    return is_readonly_type(type) || 
           is_noalias_type(type);
}

bool compatible_types(const char* expected, const char* actual)
{
    if (!strstr(expected, "readonly") && strstr(actual, "readonly"))
        return false;

    if (!strstr(expected, "noalias") && strstr(actual, "noalias"))
        return false;

    const char* e = strrchr(expected, ' ');
    const char* a = strrchr(actual, ' ');

    return !strcmp(e ? e + 1 : expected, a ? a + 1 : actual);
}
