#include "runner.h"

Type types[TYPES_LENGTH] =
{
    [0]  = { "Bool",           "bool",                                     "false",     NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   1,  1, Binary_Operator_Tag_logical_or | Binary_Operator_Tag_logical_and | Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal                                                                                                                                                                                                                                                                                                                       },
    [1]  = { "I8",             "i8",                                       "0",         "integer",  "Integer",  "-128",                 "127",                  "-129",                 "128",                  1,  1,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    [2]  = { "I16",            "i16",                                      "0",         "integer",  "Integer",  "-32768",               "32767",                "-32769",               "32768",                2,  2,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    [3]  = { "I32",            "i32",                                      "0",         "integer",  "Integer",  "-2147483648",          "2147483647",           "-2147483649",          "2147483648",           4,  4,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    [4]  = { "I64",            "i64",                                      "0",         "integer",  "Integer",  "-9223372036854775808", "9223372036854775807",  "-9223372036854775809", "9223372036854775808",  8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    [5]  = { "U8",             "u8",                                       "0",         "integer",  "Integer",  "0",                    "255",                  NULL,                   "256",                  1,  1,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    [6]  = { "U16",            "u16",                                      "0",         "integer",  "Integer",  "0",                    "65535",                NULL,                   "65_536",               2,  2,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    [7]  = { "U32",            "u32",                                      "0",         "integer",  "Integer",  "0",                    "4294967295",           NULL,                   "4294967296",           4,  4,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    [8]  = { "U64",            "u64",                                      "0",         "integer",  "Integer",  "0",                    "18446744073709551615", NULL,                   "18446744073709551616", 8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    [9]  = { "F32",            "f32",                                      "0.0",       "float",    "Float",    NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus                                                                    | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo                                                                                                      },
    [10] = { "F64",            "f64",                                      "0.0",       "float",    "Float",    NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than | Binary_Operator_Tag_plus | Binary_Operator_Tag_minus                                                                    | Binary_Operator_Tag_multiply | Binary_Operator_Tag_divide | Binary_Operator_Tag_modulo                                                                                                      },
    [11] = { "Enumeration",    "enumeration",                              NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                        | Binary_Operator_Tag_bitwise_or | Binary_Operator_Tag_bitwise_xor                                                                                          | Binary_Operator_Tag_bitwise_and | Binary_Operator_Tag_left_shift | Binary_Operator_Tag_right_shift },
    [12] = { "Union",          "monomorphic_union",                        "{ a = 0 }", "compound", "Compound", NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
    [13] = { "Union[I32]",     "polymorphic_union",                        "{ a = 0 }", "compound", "Compound", NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
    [14] = { "Structure",      "monomorphic_structure",                    "{ a = 0 }", "compound", "Compound", NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
    [15] = { "Structure[I32]", "polymorphic_structure",                    "{ a = 0 }", "compound", "Compound", NULL,                   NULL,                   NULL,                   NULL,                   4,  4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
    [16] = { "#I32",           "pointer",                                  NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [17] = { "#$I32",          "pointer_writable",                         NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [18] = { "#?I32",          "pointer_readable",                         NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [19] = { "#?$I32",         "pointer_readable_writable",                NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [20] = { "#!I32",          "pointer_alias",                            NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [21] = { "#!$I32",         "pointer_alias_writable",                   NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [22] = { "#!?I32",         "pointer_alias_readable",                   NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [23] = { "#!?$I32",        "pointer_alias_readable_writable",          NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [24] = { "#`I32",          "pointer_retained",                         NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [25] = { "#`$I32",         "pointer_retained_writable",                NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [26] = { "#`?I32",         "pointer_retained_readable",                NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [27] = { "#`?$I32",        "pointer_retained_readable_writable",       NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [28] = { "#`!I32",         "pointer_retained_alias",                   NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [29] = { "#`!$I32",        "pointer_retained_alias_writable",          NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [30] = { "#`!?I32",        "pointer_retained_alias_readable",          NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [31] = { "#`!?$I32",       "pointer_retained_alias_readable_writable", NULL,        NULL,       NULL,       NULL,                   NULL,                   NULL,                   NULL,                   8,  8,                                                                    Binary_Operator_Tag_equal_equal | Binary_Operator_Tag_not_equal | Binary_Operator_Tag_less_than_or_equal | Binary_Operator_Tag_greater_than_or_equal | Binary_Operator_Tag_less_than | Binary_Operator_Tag_greater_than                                                                                                                                                                                                                                                                                                                         },
    [32] = { "[]I32",          "dynamic_array",                            NULL,        "array",    "Array",    NULL,                   NULL,                   NULL,                   NULL,                   0,  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
    [32] = { "[4]I32",         "fixed_array",                              "{ 0 }",     "array",    "Array",    NULL,                   NULL,                   NULL,                   NULL,                   16, 16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
};

bool is_readable_type(uint8_t index)
{
    return index != 16 &&
           index != 17 &&
           index != 20 &&
           index != 21 &&
           index != 24 &&
           index != 25 &&
           index != 28 &&
           index != 29;
}

bool is_writable_type(uint8_t index)
{
    return index != 16 &&
           index != 18 &&
           index != 20 &&
           index != 22 &&
           index != 24 &&
           index != 26 &&
           index != 28 &&
           index != 30;
}

bool pointer_is_retained(uint8_t index)
{
    return index >= 24 && index <= 31;
}

bool pointer_type_is_compatible_with(uint8_t lhs_index, uint8_t rhs_index)
{
    switch (rhs_index)
    {
        case 16: // pointer
            return lhs_index >= 16 && lhs_index <= 31;

        case 17: // pointer_writable
            return lhs_index == 17 || lhs_index == 19 || lhs_index == 21 || lhs_index == 23 || 
                   lhs_index == 25 || lhs_index == 27 || lhs_index == 29 || lhs_index == 31;

        case 18: // pointer_readable
            return lhs_index == 18 || lhs_index == 19 || lhs_index == 22 || lhs_index == 23 ||
                   lhs_index == 26 || lhs_index == 27 || lhs_index == 30 || lhs_index == 31;

        case 19: // pointer_readable_writable
            return lhs_index == 19 || lhs_index == 23 || lhs_index == 27 || lhs_index == 31;

        case 20: // pointer_alias
            return lhs_index >= 20 && lhs_index <= 23 ||
                   lhs_index >= 28 && lhs_index <= 31;

        case 21: // pointer_alias_writable
            return lhs_index == 21 || lhs_index == 23 || lhs_index == 29 || lhs_index == 31;

        case 22: // pointer_alias_readable
            return lhs_index == 22 || lhs_index == 23 || lhs_index == 30 || lhs_index == 31;

        case 23: // pointer_alias_readable_writable
            return lhs_index == 23 || lhs_index == 31;

        case 24: // pointer_retained
            return lhs_index >= 24 && lhs_index <= 31;

        case 25: // pointer_retained_writable:
            return lhs_index == 25 || lhs_index == 27 || lhs_index == 29 || lhs_index == 31;

        case 26: // pointer_retained_readable
            return lhs_index == 26 || lhs_index == 27 || lhs_index == 30 || lhs_index == 31;

        case 27: // pointer_retained_readable_writable
            return lhs_index == 27 || lhs_index == 31;

        case 28: // pointer_retained_alias
            return lhs_index >= 28 && lhs_index <= 31;

        case 29: // pointer_retained_alias_writable
            return lhs_index == 29 || lhs_index == 31;

        case 30: // pointer_retained_alias_readable
            return lhs_index == 30 || lhs_index == 31;

        case 31: // pointer_retained_alias_readable_writable
            return lhs_index == 31;

        default:
            return false;
    }
}
